// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: dfs.proto

package messages

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SplitMode int32

const (
	SplitMode_SPLIT_MODE_UNSPECIFIED SplitMode = 0
	SplitMode_TEXT_LINES             SplitMode = 1
	SplitMode_BINARY_CHUNKS          SplitMode = 2
)

// Enum value maps for SplitMode.
var (
	SplitMode_name = map[int32]string{
		0: "SPLIT_MODE_UNSPECIFIED",
		1: "TEXT_LINES",
		2: "BINARY_CHUNKS",
	}
	SplitMode_value = map[string]int32{
		"SPLIT_MODE_UNSPECIFIED": 0,
		"TEXT_LINES":             1,
		"BINARY_CHUNKS":          2,
	}
)

func (x SplitMode) Enum() *SplitMode {
	p := new(SplitMode)
	*p = x
	return p
}

func (x SplitMode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SplitMode) Descriptor() protoreflect.EnumDescriptor {
	return file_dfs_proto_enumTypes[0].Descriptor()
}

func (SplitMode) Type() protoreflect.EnumType {
	return &file_dfs_proto_enumTypes[0]
}

func (x SplitMode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SplitMode.Descriptor instead.
func (SplitMode) EnumDescriptor() ([]byte, []int) {
	return file_dfs_proto_rawDescGZIP(), []int{0}
}

// *
// Storage -> Controller
// Sent when a Storage node just started
type RegisterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hostname      string                 `protobuf:"bytes,1,opt,name=hostname,proto3" json:"hostname,omitempty"`                     // hostname or IP
	Port          int32                  `protobuf:"varint,2,opt,name=port,proto3" json:"port,omitempty"`                            // listening port
	FreeSpace     uint64                 `protobuf:"varint,3,opt,name=free_space,json=freeSpace,proto3" json:"free_space,omitempty"` // available disk space (bytes)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterRequest) Reset() {
	*x = RegisterRequest{}
	mi := &file_dfs_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRequest) ProtoMessage() {}

func (x *RegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dfs_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRequest.ProtoReflect.Descriptor instead.
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return file_dfs_proto_rawDescGZIP(), []int{0}
}

func (x *RegisterRequest) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *RegisterRequest) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *RegisterRequest) GetFreeSpace() uint64 {
	if x != nil {
		return x.FreeSpace
	}
	return 0
}

// Controller -> Storage
type RegisterResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	NodeId        uint32                 `protobuf:"varint,2,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"` // unique ID for this node
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`                  // empty if ok=True otherwise error message
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterResponse) Reset() {
	*x = RegisterResponse{}
	mi := &file_dfs_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterResponse) ProtoMessage() {}

func (x *RegisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dfs_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterResponse.ProtoReflect.Descriptor instead.
func (*RegisterResponse) Descriptor() ([]byte, []int) {
	return file_dfs_proto_rawDescGZIP(), []int{1}
}

func (x *RegisterResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *RegisterResponse) GetNodeId() uint32 {
	if x != nil {
		return x.NodeId
	}
	return 0
}

func (x *RegisterResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// Storage -> Controller
// Send every 5 seconds
// Piggyback replication response if Controller made a replication request
type Heartbeat struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        uint32                 `protobuf:"varint,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	FreeSpace     uint64                 `protobuf:"varint,2,opt,name=free_space,json=freeSpace,proto3" json:"free_space,omitempty"`    // free disk space (bytes)
	NumRequest    uint64                 `protobuf:"varint,3,opt,name=num_request,json=numRequest,proto3" json:"num_request,omitempty"` // number of request handled
	NewChunks     []*ChunkInfo           `protobuf:"bytes,4,rep,name=new_chunks,json=newChunks,proto3" json:"new_chunks,omitempty"`     // ack that a replication request is successful
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Heartbeat) Reset() {
	*x = Heartbeat{}
	mi := &file_dfs_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Heartbeat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Heartbeat) ProtoMessage() {}

func (x *Heartbeat) ProtoReflect() protoreflect.Message {
	mi := &file_dfs_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Heartbeat.ProtoReflect.Descriptor instead.
func (*Heartbeat) Descriptor() ([]byte, []int) {
	return file_dfs_proto_rawDescGZIP(), []int{2}
}

func (x *Heartbeat) GetNodeId() uint32 {
	if x != nil {
		return x.NodeId
	}
	return 0
}

func (x *Heartbeat) GetFreeSpace() uint64 {
	if x != nil {
		return x.FreeSpace
	}
	return 0
}

func (x *Heartbeat) GetNumRequest() uint64 {
	if x != nil {
		return x.NumRequest
	}
	return 0
}

func (x *Heartbeat) GetNewChunks() []*ChunkInfo {
	if x != nil {
		return x.NewChunks
	}
	return nil
}

// Controller -> Storage
// Piggback replication request, if a node failed
type HeartbeatResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Ack              bool                   `protobuf:"varint,1,opt,name=ack,proto3" json:"ack,omitempty"`
	ReplicateRequest []*ReplicateRequest    `protobuf:"bytes,2,rep,name=replicate_request,json=replicateRequest,proto3" json:"replicate_request,omitempty"` // maybe carry replication request here?
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *HeartbeatResponse) Reset() {
	*x = HeartbeatResponse{}
	mi := &file_dfs_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatResponse) ProtoMessage() {}

func (x *HeartbeatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dfs_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatResponse.ProtoReflect.Descriptor instead.
func (*HeartbeatResponse) Descriptor() ([]byte, []int) {
	return file_dfs_proto_rawDescGZIP(), []int{3}
}

func (x *HeartbeatResponse) GetAck() bool {
	if x != nil {
		return x.Ack
	}
	return false
}

func (x *HeartbeatResponse) GetReplicateRequest() []*ReplicateRequest {
	if x != nil {
		return x.ReplicateRequest
	}
	return nil
}

// Controller -> Storage
type ReplicateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SrcHost       string                 `protobuf:"bytes,1,opt,name=src_host,json=srcHost,proto3" json:"src_host,omitempty"`  // host to replicate chunk from
	SrcPort       int32                  `protobuf:"varint,2,opt,name=src_port,json=srcPort,proto3" json:"src_port,omitempty"` // port the host is listening on
	ChunkInfo     *ChunkInfo             `protobuf:"bytes,3,opt,name=chunk_info,json=chunkInfo,proto3" json:"chunk_info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReplicateRequest) Reset() {
	*x = ReplicateRequest{}
	mi := &file_dfs_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReplicateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplicateRequest) ProtoMessage() {}

func (x *ReplicateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dfs_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReplicateRequest.ProtoReflect.Descriptor instead.
func (*ReplicateRequest) Descriptor() ([]byte, []int) {
	return file_dfs_proto_rawDescGZIP(), []int{4}
}

func (x *ReplicateRequest) GetSrcHost() string {
	if x != nil {
		return x.SrcHost
	}
	return ""
}

func (x *ReplicateRequest) GetSrcPort() int32 {
	if x != nil {
		return x.SrcPort
	}
	return 0
}

func (x *ReplicateRequest) GetChunkInfo() *ChunkInfo {
	if x != nil {
		return x.ChunkInfo
	}
	return nil
}

// Represents a chunk of a file
type ChunkInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Filename      string                 `protobuf:"bytes,1,opt,name=filename,proto3" json:"filename,omitempty"`
	ChunkIndex    uint32                 `protobuf:"varint,2,opt,name=chunk_index,json=chunkIndex,proto3" json:"chunk_index,omitempty"` // chunk number
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChunkInfo) Reset() {
	*x = ChunkInfo{}
	mi := &file_dfs_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChunkInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChunkInfo) ProtoMessage() {}

func (x *ChunkInfo) ProtoReflect() protoreflect.Message {
	mi := &file_dfs_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChunkInfo.ProtoReflect.Descriptor instead.
func (*ChunkInfo) Descriptor() ([]byte, []int) {
	return file_dfs_proto_rawDescGZIP(), []int{5}
}

func (x *ChunkInfo) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *ChunkInfo) GetChunkIndex() uint32 {
	if x != nil {
		return x.ChunkIndex
	}
	return 0
}

// Represents a storage node's address
type NodeInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        uint32                 `protobuf:"varint,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Hostname      string                 `protobuf:"bytes,2,opt,name=hostname,proto3" json:"hostname,omitempty"`
	Port          int32                  `protobuf:"varint,3,opt,name=port,proto3" json:"port,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeInfo) Reset() {
	*x = NodeInfo{}
	mi := &file_dfs_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeInfo) ProtoMessage() {}

func (x *NodeInfo) ProtoReflect() protoreflect.Message {
	mi := &file_dfs_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeInfo.ProtoReflect.Descriptor instead.
func (*NodeInfo) Descriptor() ([]byte, []int) {
	return file_dfs_proto_rawDescGZIP(), []int{6}
}

func (x *NodeInfo) GetNodeId() uint32 {
	if x != nil {
		return x.NodeId
	}
	return 0
}

func (x *NodeInfo) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *NodeInfo) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

// Represents where to send a specific chunk
type ChunkMapping struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChunkInfo     *ChunkInfo             `protobuf:"bytes,1,opt,name=chunk_info,json=chunkInfo,proto3" json:"chunk_info,omitempty"` // which chunk
	Nodes         []*NodeInfo            `protobuf:"bytes,2,rep,name=nodes,proto3" json:"nodes,omitempty"`                          // locations of primary & replicas (e.g. [A, B, C])
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChunkMapping) Reset() {
	*x = ChunkMapping{}
	mi := &file_dfs_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChunkMapping) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChunkMapping) ProtoMessage() {}

func (x *ChunkMapping) ProtoReflect() protoreflect.Message {
	mi := &file_dfs_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChunkMapping.ProtoReflect.Descriptor instead.
func (*ChunkMapping) Descriptor() ([]byte, []int) {
	return file_dfs_proto_rawDescGZIP(), []int{7}
}

func (x *ChunkMapping) GetChunkInfo() *ChunkInfo {
	if x != nil {
		return x.ChunkInfo
	}
	return nil
}

func (x *ChunkMapping) GetNodes() []*NodeInfo {
	if x != nil {
		return x.Nodes
	}
	return nil
}

// Client -> Controller
type StoreRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Filename      string                 `protobuf:"bytes,1,opt,name=filename,proto3" json:"filename,omitempty"`
	ChunkCount    uint32                 `protobuf:"varint,2,opt,name=chunk_count,json=chunkCount,proto3" json:"chunk_count,omitempty"`
	ChunkSize     uint64                 `protobuf:"varint,3,opt,name=chunk_size,json=chunkSize,proto3" json:"chunk_size,omitempty"` // to be consistent with freespace in Heartbeat, also uint64
	FileSize      uint64                 `protobuf:"varint,4,opt,name=file_size,json=fileSize,proto3" json:"file_size,omitempty"`    // total file size
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StoreRequest) Reset() {
	*x = StoreRequest{}
	mi := &file_dfs_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StoreRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StoreRequest) ProtoMessage() {}

func (x *StoreRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dfs_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StoreRequest.ProtoReflect.Descriptor instead.
func (*StoreRequest) Descriptor() ([]byte, []int) {
	return file_dfs_proto_rawDescGZIP(), []int{8}
}

func (x *StoreRequest) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *StoreRequest) GetChunkCount() uint32 {
	if x != nil {
		return x.ChunkCount
	}
	return 0
}

func (x *StoreRequest) GetChunkSize() uint64 {
	if x != nil {
		return x.ChunkSize
	}
	return 0
}

func (x *StoreRequest) GetFileSize() uint64 {
	if x != nil {
		return x.FileSize
	}
	return 0
}

// Controller -> Client
type StoreResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"` // empty if ok=true
	Destinations  []*ChunkMapping        `protobuf:"bytes,3,rep,name=destinations,proto3" json:"destinations,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StoreResponse) Reset() {
	*x = StoreResponse{}
	mi := &file_dfs_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StoreResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StoreResponse) ProtoMessage() {}

func (x *StoreResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dfs_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StoreResponse.ProtoReflect.Descriptor instead.
func (*StoreResponse) Descriptor() ([]byte, []int) {
	return file_dfs_proto_rawDescGZIP(), []int{9}
}

func (x *StoreResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *StoreResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *StoreResponse) GetDestinations() []*ChunkMapping {
	if x != nil {
		return x.Destinations
	}
	return nil
}

// Client -> Controller
type RetrieveRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Filename      string                 `protobuf:"bytes,1,opt,name=filename,proto3" json:"filename,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RetrieveRequest) Reset() {
	*x = RetrieveRequest{}
	mi := &file_dfs_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RetrieveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RetrieveRequest) ProtoMessage() {}

func (x *RetrieveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dfs_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RetrieveRequest.ProtoReflect.Descriptor instead.
func (*RetrieveRequest) Descriptor() ([]byte, []int) {
	return file_dfs_proto_rawDescGZIP(), []int{10}
}

func (x *RetrieveRequest) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

// Controller -> Client
type RetrieveResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"` // empty if ok=true
	Locations     []*ChunkMapping        `protobuf:"bytes,3,rep,name=locations,proto3" json:"locations,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RetrieveResponse) Reset() {
	*x = RetrieveResponse{}
	mi := &file_dfs_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RetrieveResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RetrieveResponse) ProtoMessage() {}

func (x *RetrieveResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dfs_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RetrieveResponse.ProtoReflect.Descriptor instead.
func (*RetrieveResponse) Descriptor() ([]byte, []int) {
	return file_dfs_proto_rawDescGZIP(), []int{11}
}

func (x *RetrieveResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *RetrieveResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *RetrieveResponse) GetLocations() []*ChunkMapping {
	if x != nil {
		return x.Locations
	}
	return nil
}

// Client -> Controller
// Returns metadata for a single completed file.
type StatFileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Filename      string                 `protobuf:"bytes,1,opt,name=filename,proto3" json:"filename,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatFileRequest) Reset() {
	*x = StatFileRequest{}
	mi := &file_dfs_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatFileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatFileRequest) ProtoMessage() {}

func (x *StatFileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dfs_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatFileRequest.ProtoReflect.Descriptor instead.
func (*StatFileRequest) Descriptor() ([]byte, []int) {
	return file_dfs_proto_rawDescGZIP(), []int{12}
}

func (x *StatFileRequest) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

// Controller -> Client
type StatFileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"` // empty if ok=true
	Filename      string                 `protobuf:"bytes,3,opt,name=filename,proto3" json:"filename,omitempty"`
	FileSize      uint64                 `protobuf:"varint,4,opt,name=file_size,json=fileSize,proto3" json:"file_size,omitempty"`
	ChunkSize     uint64                 `protobuf:"varint,5,opt,name=chunk_size,json=chunkSize,proto3" json:"chunk_size,omitempty"`
	ChunkCount    uint32                 `protobuf:"varint,6,opt,name=chunk_count,json=chunkCount,proto3" json:"chunk_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatFileResponse) Reset() {
	*x = StatFileResponse{}
	mi := &file_dfs_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatFileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatFileResponse) ProtoMessage() {}

func (x *StatFileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dfs_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatFileResponse.ProtoReflect.Descriptor instead.
func (*StatFileResponse) Descriptor() ([]byte, []int) {
	return file_dfs_proto_rawDescGZIP(), []int{13}
}

func (x *StatFileResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *StatFileResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *StatFileResponse) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *StatFileResponse) GetFileSize() uint64 {
	if x != nil {
		return x.FileSize
	}
	return 0
}

func (x *StatFileResponse) GetChunkSize() uint64 {
	if x != nil {
		return x.ChunkSize
	}
	return 0
}

func (x *StatFileResponse) GetChunkCount() uint32 {
	if x != nil {
		return x.ChunkCount
	}
	return 0
}

type InputSplit struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	SplitIndex         uint32                 `protobuf:"varint,1,opt,name=split_index,json=splitIndex,proto3" json:"split_index,omitempty"`
	Filename           string                 `protobuf:"bytes,2,opt,name=filename,proto3" json:"filename,omitempty"`
	StartOffset        uint64                 `protobuf:"varint,3,opt,name=start_offset,json=startOffset,proto3" json:"start_offset,omitempty"`
	EndOffsetExclusive uint64                 `protobuf:"varint,4,opt,name=end_offset_exclusive,json=endOffsetExclusive,proto3" json:"end_offset_exclusive,omitempty"`
	StartLineNumber    uint64                 `protobuf:"varint,5,opt,name=start_line_number,json=startLineNumber,proto3" json:"start_line_number,omitempty"` // zero-based; 0 for binary splits
	PreferredNodes     []*NodeInfo            `protobuf:"bytes,6,rep,name=preferred_nodes,json=preferredNodes,proto3" json:"preferred_nodes,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *InputSplit) Reset() {
	*x = InputSplit{}
	mi := &file_dfs_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InputSplit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InputSplit) ProtoMessage() {}

func (x *InputSplit) ProtoReflect() protoreflect.Message {
	mi := &file_dfs_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InputSplit.ProtoReflect.Descriptor instead.
func (*InputSplit) Descriptor() ([]byte, []int) {
	return file_dfs_proto_rawDescGZIP(), []int{14}
}

func (x *InputSplit) GetSplitIndex() uint32 {
	if x != nil {
		return x.SplitIndex
	}
	return 0
}

func (x *InputSplit) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *InputSplit) GetStartOffset() uint64 {
	if x != nil {
		return x.StartOffset
	}
	return 0
}

func (x *InputSplit) GetEndOffsetExclusive() uint64 {
	if x != nil {
		return x.EndOffsetExclusive
	}
	return 0
}

func (x *InputSplit) GetStartLineNumber() uint64 {
	if x != nil {
		return x.StartLineNumber
	}
	return 0
}

func (x *InputSplit) GetPreferredNodes() []*NodeInfo {
	if x != nil {
		return x.PreferredNodes
	}
	return nil
}

// Client -> Controller
// Ask the DFS to expose logical read splits for MapReduce.
type GetInputSplitsRequest struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	Filename              string                 `protobuf:"bytes,1,opt,name=filename,proto3" json:"filename,omitempty"`
	SplitMode             SplitMode              `protobuf:"varint,2,opt,name=split_mode,json=splitMode,proto3,enum=SplitMode" json:"split_mode,omitempty"`
	DesiredSplitSizeBytes uint64                 `protobuf:"varint,3,opt,name=desired_split_size_bytes,json=desiredSplitSizeBytes,proto3" json:"desired_split_size_bytes,omitempty"` // 0 means "use DFS chunk size"
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *GetInputSplitsRequest) Reset() {
	*x = GetInputSplitsRequest{}
	mi := &file_dfs_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetInputSplitsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetInputSplitsRequest) ProtoMessage() {}

func (x *GetInputSplitsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dfs_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetInputSplitsRequest.ProtoReflect.Descriptor instead.
func (*GetInputSplitsRequest) Descriptor() ([]byte, []int) {
	return file_dfs_proto_rawDescGZIP(), []int{15}
}

func (x *GetInputSplitsRequest) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *GetInputSplitsRequest) GetSplitMode() SplitMode {
	if x != nil {
		return x.SplitMode
	}
	return SplitMode_SPLIT_MODE_UNSPECIFIED
}

func (x *GetInputSplitsRequest) GetDesiredSplitSizeBytes() uint64 {
	if x != nil {
		return x.DesiredSplitSizeBytes
	}
	return 0
}

// Controller -> Client
type GetInputSplitsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	Splits        []*InputSplit          `protobuf:"bytes,3,rep,name=splits,proto3" json:"splits,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetInputSplitsResponse) Reset() {
	*x = GetInputSplitsResponse{}
	mi := &file_dfs_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetInputSplitsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetInputSplitsResponse) ProtoMessage() {}

func (x *GetInputSplitsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dfs_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetInputSplitsResponse.ProtoReflect.Descriptor instead.
func (*GetInputSplitsResponse) Descriptor() ([]byte, []int) {
	return file_dfs_proto_rawDescGZIP(), []int{16}
}

func (x *GetInputSplitsResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *GetInputSplitsResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *GetInputSplitsResponse) GetSplits() []*InputSplit {
	if x != nil {
		return x.Splits
	}
	return nil
}

// Client -> Controller
type DeleteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Filename      string                 `protobuf:"bytes,1,opt,name=filename,proto3" json:"filename,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteRequest) Reset() {
	*x = DeleteRequest{}
	mi := &file_dfs_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRequest) ProtoMessage() {}

func (x *DeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dfs_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRequest.ProtoReflect.Descriptor instead.
func (*DeleteRequest) Descriptor() ([]byte, []int) {
	return file_dfs_proto_rawDescGZIP(), []int{17}
}

func (x *DeleteRequest) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

// Controller -> Client
type DeleteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`      // success or fail
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"` // empty if ok=true
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteResponse) Reset() {
	*x = DeleteResponse{}
	mi := &file_dfs_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteResponse) ProtoMessage() {}

func (x *DeleteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dfs_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteResponse.ProtoReflect.Descriptor instead.
func (*DeleteResponse) Descriptor() ([]byte, []int) {
	return file_dfs_proto_rawDescGZIP(), []int{18}
}

func (x *DeleteResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *DeleteResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// Client -> Controller
// List all stored files
type ListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRequest) Reset() {
	*x = ListRequest{}
	mi := &file_dfs_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRequest) ProtoMessage() {}

func (x *ListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dfs_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRequest.ProtoReflect.Descriptor instead.
func (*ListRequest) Descriptor() ([]byte, []int) {
	return file_dfs_proto_rawDescGZIP(), []int{19}
}

// Represents a file in the system
type FileInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Filename      string                 `protobuf:"bytes,1,opt,name=filename,proto3" json:"filename,omitempty"`
	FileSize      uint64                 `protobuf:"varint,2,opt,name=file_size,json=fileSize,proto3" json:"file_size,omitempty"`
	ChunkCount    uint32                 `protobuf:"varint,3,opt,name=chunk_count,json=chunkCount,proto3" json:"chunk_count,omitempty"` // how many chunks does this file have
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileInfo) Reset() {
	*x = FileInfo{}
	mi := &file_dfs_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileInfo) ProtoMessage() {}

func (x *FileInfo) ProtoReflect() protoreflect.Message {
	mi := &file_dfs_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileInfo.ProtoReflect.Descriptor instead.
func (*FileInfo) Descriptor() ([]byte, []int) {
	return file_dfs_proto_rawDescGZIP(), []int{20}
}

func (x *FileInfo) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *FileInfo) GetFileSize() uint64 {
	if x != nil {
		return x.FileSize
	}
	return 0
}

func (x *FileInfo) GetChunkCount() uint32 {
	if x != nil {
		return x.ChunkCount
	}
	return 0
}

// Controller -> Client
type ListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	Files         []*FileInfo            `protobuf:"bytes,3,rep,name=files,proto3" json:"files,omitempty"` // empty if no files stored
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListResponse) Reset() {
	*x = ListResponse{}
	mi := &file_dfs_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListResponse) ProtoMessage() {}

func (x *ListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dfs_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListResponse.ProtoReflect.Descriptor instead.
func (*ListResponse) Descriptor() ([]byte, []int) {
	return file_dfs_proto_rawDescGZIP(), []int{21}
}

func (x *ListResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *ListResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *ListResponse) GetFiles() []*FileInfo {
	if x != nil {
		return x.Files
	}
	return nil
}

// Client -> Controller
// Request for node list + disk space + request counts
type ClusterInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClusterInfoRequest) Reset() {
	*x = ClusterInfoRequest{}
	mi := &file_dfs_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClusterInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClusterInfoRequest) ProtoMessage() {}

func (x *ClusterInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dfs_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClusterInfoRequest.ProtoReflect.Descriptor instead.
func (*ClusterInfoRequest) Descriptor() ([]byte, []int) {
	return file_dfs_proto_rawDescGZIP(), []int{22}
}

// Represents a storage node's runtime stats
type NodeStats struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeInfo      *NodeInfo              `protobuf:"bytes,1,opt,name=node_info,json=nodeInfo,proto3" json:"node_info,omitempty"`           // id, hostname, port
	FreeSpace     uint64                 `protobuf:"varint,2,opt,name=free_space,json=freeSpace,proto3" json:"free_space,omitempty"`       // free space
	NumRequests   uint64                 `protobuf:"varint,3,opt,name=num_requests,json=numRequests,proto3" json:"num_requests,omitempty"` // request count
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeStats) Reset() {
	*x = NodeStats{}
	mi := &file_dfs_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeStats) ProtoMessage() {}

func (x *NodeStats) ProtoReflect() protoreflect.Message {
	mi := &file_dfs_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeStats.ProtoReflect.Descriptor instead.
func (*NodeStats) Descriptor() ([]byte, []int) {
	return file_dfs_proto_rawDescGZIP(), []int{23}
}

func (x *NodeStats) GetNodeInfo() *NodeInfo {
	if x != nil {
		return x.NodeInfo
	}
	return nil
}

func (x *NodeStats) GetFreeSpace() uint64 {
	if x != nil {
		return x.FreeSpace
	}
	return 0
}

func (x *NodeStats) GetNumRequests() uint64 {
	if x != nil {
		return x.NumRequests
	}
	return 0
}

// Controller -> Client
type ClusterInfoResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	NodeStats      []*NodeStats           `protobuf:"bytes,1,rep,name=node_stats,json=nodeStats,proto3" json:"node_stats,omitempty"`
	TotalFreeSpace uint64                 `protobuf:"varint,2,opt,name=total_free_space,json=totalFreeSpace,proto3" json:"total_free_space,omitempty"` // total across all nodes
	TotalRequests  uint64                 `protobuf:"varint,3,opt,name=total_requests,json=totalRequests,proto3" json:"total_requests,omitempty"`      // total request count
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ClusterInfoResponse) Reset() {
	*x = ClusterInfoResponse{}
	mi := &file_dfs_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClusterInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClusterInfoResponse) ProtoMessage() {}

func (x *ClusterInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dfs_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClusterInfoResponse.ProtoReflect.Descriptor instead.
func (*ClusterInfoResponse) Descriptor() ([]byte, []int) {
	return file_dfs_proto_rawDescGZIP(), []int{24}
}

func (x *ClusterInfoResponse) GetNodeStats() []*NodeStats {
	if x != nil {
		return x.NodeStats
	}
	return nil
}

func (x *ClusterInfoResponse) GetTotalFreeSpace() uint64 {
	if x != nil {
		return x.TotalFreeSpace
	}
	return 0
}

func (x *ClusterInfoResponse) GetTotalRequests() uint64 {
	if x != nil {
		return x.TotalRequests
	}
	return 0
}

// Client -> Storage AND Storage -> Storage
type StoreChunkRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChunkInfo     *ChunkInfo             `protobuf:"bytes,1,opt,name=chunk_info,json=chunkInfo,proto3" json:"chunk_info,omitempty"` // filename + chunk index
	ChunkData     []byte                 `protobuf:"bytes,2,opt,name=chunk_data,json=chunkData,proto3" json:"chunk_data,omitempty"`
	Checksum      []byte                 `protobuf:"bytes,3,opt,name=checksum,proto3" json:"checksum,omitempty"`
	Pipeline      []*NodeInfo            `protobuf:"bytes,4,rep,name=pipeline,proto3" json:"pipeline,omitempty"` // next remaining nodes in the pipeline
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StoreChunkRequest) Reset() {
	*x = StoreChunkRequest{}
	mi := &file_dfs_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StoreChunkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StoreChunkRequest) ProtoMessage() {}

func (x *StoreChunkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dfs_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StoreChunkRequest.ProtoReflect.Descriptor instead.
func (*StoreChunkRequest) Descriptor() ([]byte, []int) {
	return file_dfs_proto_rawDescGZIP(), []int{25}
}

func (x *StoreChunkRequest) GetChunkInfo() *ChunkInfo {
	if x != nil {
		return x.ChunkInfo
	}
	return nil
}

func (x *StoreChunkRequest) GetChunkData() []byte {
	if x != nil {
		return x.ChunkData
	}
	return nil
}

func (x *StoreChunkRequest) GetChecksum() []byte {
	if x != nil {
		return x.Checksum
	}
	return nil
}

func (x *StoreChunkRequest) GetPipeline() []*NodeInfo {
	if x != nil {
		return x.Pipeline
	}
	return nil
}

// Storage -> Client
type StoreChunkResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`                               // success or fail
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`                          // empty if ok=true
	ChunkInfo     *ChunkInfo             `protobuf:"bytes,3,opt,name=chunk_info,json=chunkInfo,proto3" json:"chunk_info,omitempty"` // which chunk was successfully saved (useful for error reporting)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StoreChunkResponse) Reset() {
	*x = StoreChunkResponse{}
	mi := &file_dfs_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StoreChunkResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StoreChunkResponse) ProtoMessage() {}

func (x *StoreChunkResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dfs_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StoreChunkResponse.ProtoReflect.Descriptor instead.
func (*StoreChunkResponse) Descriptor() ([]byte, []int) {
	return file_dfs_proto_rawDescGZIP(), []int{26}
}

func (x *StoreChunkResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *StoreChunkResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *StoreChunkResponse) GetChunkInfo() *ChunkInfo {
	if x != nil {
		return x.ChunkInfo
	}
	return nil
}

// *
// Client -> Storage
// Retrieve a chunk from this node
// Include `replica_hints` in case the chunk is corrupted
type RetrieveChunkRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChunkInfo     *ChunkInfo             `protobuf:"bytes,1,opt,name=chunk_info,json=chunkInfo,proto3" json:"chunk_info,omitempty"`
	ReplicaHints  []*NodeInfo            `protobuf:"bytes,2,rep,name=replica_hints,json=replicaHints,proto3" json:"replica_hints,omitempty"` // for fallback if the chunk is corrupted
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RetrieveChunkRequest) Reset() {
	*x = RetrieveChunkRequest{}
	mi := &file_dfs_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RetrieveChunkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RetrieveChunkRequest) ProtoMessage() {}

func (x *RetrieveChunkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dfs_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RetrieveChunkRequest.ProtoReflect.Descriptor instead.
func (*RetrieveChunkRequest) Descriptor() ([]byte, []int) {
	return file_dfs_proto_rawDescGZIP(), []int{27}
}

func (x *RetrieveChunkRequest) GetChunkInfo() *ChunkInfo {
	if x != nil {
		return x.ChunkInfo
	}
	return nil
}

func (x *RetrieveChunkRequest) GetReplicaHints() []*NodeInfo {
	if x != nil {
		return x.ReplicaHints
	}
	return nil
}

// *
// Storage -> Client
type RetrieveChunkResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"` // empty if ok=true
	ChunkData     []byte                 `protobuf:"bytes,3,opt,name=chunk_data,json=chunkData,proto3" json:"chunk_data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RetrieveChunkResponse) Reset() {
	*x = RetrieveChunkResponse{}
	mi := &file_dfs_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RetrieveChunkResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RetrieveChunkResponse) ProtoMessage() {}

func (x *RetrieveChunkResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dfs_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RetrieveChunkResponse.ProtoReflect.Descriptor instead.
func (*RetrieveChunkResponse) Descriptor() ([]byte, []int) {
	return file_dfs_proto_rawDescGZIP(), []int{28}
}

func (x *RetrieveChunkResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *RetrieveChunkResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *RetrieveChunkResponse) GetChunkData() []byte {
	if x != nil {
		return x.ChunkData
	}
	return nil
}

// Client/Controller -> Storage
// Read a verified byte range from one chunk without changing the on-disk
// storage format. Logical file-range reads can be composed from this primitive.
type ReadChunkRangeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChunkInfo     *ChunkInfo             `protobuf:"bytes,1,opt,name=chunk_info,json=chunkInfo,proto3" json:"chunk_info,omitempty"`
	ChunkOffset   uint64                 `protobuf:"varint,2,opt,name=chunk_offset,json=chunkOffset,proto3" json:"chunk_offset,omitempty"`
	Length        uint64                 `protobuf:"varint,3,opt,name=length,proto3" json:"length,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadChunkRangeRequest) Reset() {
	*x = ReadChunkRangeRequest{}
	mi := &file_dfs_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadChunkRangeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadChunkRangeRequest) ProtoMessage() {}

func (x *ReadChunkRangeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dfs_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadChunkRangeRequest.ProtoReflect.Descriptor instead.
func (*ReadChunkRangeRequest) Descriptor() ([]byte, []int) {
	return file_dfs_proto_rawDescGZIP(), []int{29}
}

func (x *ReadChunkRangeRequest) GetChunkInfo() *ChunkInfo {
	if x != nil {
		return x.ChunkInfo
	}
	return nil
}

func (x *ReadChunkRangeRequest) GetChunkOffset() uint64 {
	if x != nil {
		return x.ChunkOffset
	}
	return 0
}

func (x *ReadChunkRangeRequest) GetLength() uint64 {
	if x != nil {
		return x.Length
	}
	return 0
}

// Storage -> Client/Controller
type ReadChunkRangeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	ChunkInfo     *ChunkInfo             `protobuf:"bytes,3,opt,name=chunk_info,json=chunkInfo,proto3" json:"chunk_info,omitempty"`
	ChunkData     []byte                 `protobuf:"bytes,4,opt,name=chunk_data,json=chunkData,proto3" json:"chunk_data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadChunkRangeResponse) Reset() {
	*x = ReadChunkRangeResponse{}
	mi := &file_dfs_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadChunkRangeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadChunkRangeResponse) ProtoMessage() {}

func (x *ReadChunkRangeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dfs_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadChunkRangeResponse.ProtoReflect.Descriptor instead.
func (*ReadChunkRangeResponse) Descriptor() ([]byte, []int) {
	return file_dfs_proto_rawDescGZIP(), []int{30}
}

func (x *ReadChunkRangeResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *ReadChunkRangeResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *ReadChunkRangeResponse) GetChunkInfo() *ChunkInfo {
	if x != nil {
		return x.ChunkInfo
	}
	return nil
}

func (x *ReadChunkRangeResponse) GetChunkData() []byte {
	if x != nil {
		return x.ChunkData
	}
	return nil
}

// Controller -> Storage
// Controller issues deletion instead of client
type DeleteChunkRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChunkInfo     *ChunkInfo             `protobuf:"bytes,1,opt,name=chunk_info,json=chunkInfo,proto3" json:"chunk_info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteChunkRequest) Reset() {
	*x = DeleteChunkRequest{}
	mi := &file_dfs_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteChunkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteChunkRequest) ProtoMessage() {}

func (x *DeleteChunkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dfs_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteChunkRequest.ProtoReflect.Descriptor instead.
func (*DeleteChunkRequest) Descriptor() ([]byte, []int) {
	return file_dfs_proto_rawDescGZIP(), []int{31}
}

func (x *DeleteChunkRequest) GetChunkInfo() *ChunkInfo {
	if x != nil {
		return x.ChunkInfo
	}
	return nil
}

type DeleteChunkResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	ChunkInfo     *ChunkInfo             `protobuf:"bytes,3,opt,name=chunk_info,json=chunkInfo,proto3" json:"chunk_info,omitempty"` // so Controller knows which chunk this ack is for
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteChunkResponse) Reset() {
	*x = DeleteChunkResponse{}
	mi := &file_dfs_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteChunkResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteChunkResponse) ProtoMessage() {}

func (x *DeleteChunkResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dfs_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteChunkResponse.ProtoReflect.Descriptor instead.
func (*DeleteChunkResponse) Descriptor() ([]byte, []int) {
	return file_dfs_proto_rawDescGZIP(), []int{32}
}

func (x *DeleteChunkResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *DeleteChunkResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *DeleteChunkResponse) GetChunkInfo() *ChunkInfo {
	if x != nil {
		return x.ChunkInfo
	}
	return nil
}

// *
// Storage -> Storage
// Request a chunk, if local copy is corrupted
type RepairChunkRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChunkInfo     *ChunkInfo             `protobuf:"bytes,1,opt,name=chunk_info,json=chunkInfo,proto3" json:"chunk_info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RepairChunkRequest) Reset() {
	*x = RepairChunkRequest{}
	mi := &file_dfs_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RepairChunkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RepairChunkRequest) ProtoMessage() {}

func (x *RepairChunkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dfs_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RepairChunkRequest.ProtoReflect.Descriptor instead.
func (*RepairChunkRequest) Descriptor() ([]byte, []int) {
	return file_dfs_proto_rawDescGZIP(), []int{33}
}

func (x *RepairChunkRequest) GetChunkInfo() *ChunkInfo {
	if x != nil {
		return x.ChunkInfo
	}
	return nil
}

// *
// Storage -> Storage
// Send a validated chunk to the requester node.
// If local copy is also corrupted, send ok=false and don't send the chunk
type RepairChunkResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"` // empty if ok=true
	ChunkInfo     *ChunkInfo             `protobuf:"bytes,3,opt,name=chunk_info,json=chunkInfo,proto3" json:"chunk_info,omitempty"`
	ChunkData     []byte                 `protobuf:"bytes,4,opt,name=chunk_data,json=chunkData,proto3" json:"chunk_data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RepairChunkResponse) Reset() {
	*x = RepairChunkResponse{}
	mi := &file_dfs_proto_msgTypes[34]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RepairChunkResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RepairChunkResponse) ProtoMessage() {}

func (x *RepairChunkResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dfs_proto_msgTypes[34]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RepairChunkResponse.ProtoReflect.Descriptor instead.
func (*RepairChunkResponse) Descriptor() ([]byte, []int) {
	return file_dfs_proto_rawDescGZIP(), []int{34}
}

func (x *RepairChunkResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *RepairChunkResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *RepairChunkResponse) GetChunkInfo() *ChunkInfo {
	if x != nil {
		return x.ChunkInfo
	}
	return nil
}

func (x *RepairChunkResponse) GetChunkData() []byte {
	if x != nil {
		return x.ChunkData
	}
	return nil
}

// *
// Storage -> Controller
// Asks for a list of nodes that holds the replica of a chunk
type ChunkLocationsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChunkInfo     *ChunkInfo             `protobuf:"bytes,1,opt,name=chunk_info,json=chunkInfo,proto3" json:"chunk_info,omitempty"` // which chunk
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChunkLocationsRequest) Reset() {
	*x = ChunkLocationsRequest{}
	mi := &file_dfs_proto_msgTypes[35]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChunkLocationsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChunkLocationsRequest) ProtoMessage() {}

func (x *ChunkLocationsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dfs_proto_msgTypes[35]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChunkLocationsRequest.ProtoReflect.Descriptor instead.
func (*ChunkLocationsRequest) Descriptor() ([]byte, []int) {
	return file_dfs_proto_rawDescGZIP(), []int{35}
}

func (x *ChunkLocationsRequest) GetChunkInfo() *ChunkInfo {
	if x != nil {
		return x.ChunkInfo
	}
	return nil
}

// *
// Controller -> Storage
// Responds with a list of nodes holding the chunk
type ChunkLocationsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	ChunkInfo     *ChunkInfo             `protobuf:"bytes,3,opt,name=chunk_info,json=chunkInfo,proto3" json:"chunk_info,omitempty"` // which chunk
	Nodes         []*NodeInfo            `protobuf:"bytes,4,rep,name=nodes,proto3" json:"nodes,omitempty"`                          // which node holds this chunk
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChunkLocationsResponse) Reset() {
	*x = ChunkLocationsResponse{}
	mi := &file_dfs_proto_msgTypes[36]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChunkLocationsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChunkLocationsResponse) ProtoMessage() {}

func (x *ChunkLocationsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dfs_proto_msgTypes[36]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChunkLocationsResponse.ProtoReflect.Descriptor instead.
func (*ChunkLocationsResponse) Descriptor() ([]byte, []int) {
	return file_dfs_proto_rawDescGZIP(), []int{36}
}

func (x *ChunkLocationsResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *ChunkLocationsResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *ChunkLocationsResponse) GetChunkInfo() *ChunkInfo {
	if x != nil {
		return x.ChunkInfo
	}
	return nil
}

func (x *ChunkLocationsResponse) GetNodes() []*NodeInfo {
	if x != nil {
		return x.Nodes
	}
	return nil
}

type Wrapper struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Msg:
	//
	//	*Wrapper_RegisterRequest
	//	*Wrapper_RegisterResponse
	//	*Wrapper_Heartbeat
	//	*Wrapper_HeartbeatResponse
	//	*Wrapper_ReplicateRequest
	//	*Wrapper_StoreRequest
	//	*Wrapper_StoreResponse
	//	*Wrapper_RetrieveRequest
	//	*Wrapper_RetrieveResponse
	//	*Wrapper_StatFileRequest
	//	*Wrapper_StatFileResponse
	//	*Wrapper_GetInputSplitsRequest
	//	*Wrapper_GetInputSplitsResponse
	//	*Wrapper_DeleteRequest
	//	*Wrapper_DeleteResponse
	//	*Wrapper_ListRequest
	//	*Wrapper_ListResponse
	//	*Wrapper_ClusterInfoRequest
	//	*Wrapper_ClusterInfoResponse
	//	*Wrapper_StoreChunkRequest
	//	*Wrapper_StoreChunkResponse
	//	*Wrapper_RetrieveChunkRequest
	//	*Wrapper_RetrieveChunkResponse
	//	*Wrapper_ReadChunkRangeRequest
	//	*Wrapper_ReadChunkRangeResponse
	//	*Wrapper_DeleteChunkRequest
	//	*Wrapper_DeleteChunkResponse
	//	*Wrapper_RepairChunkRequest
	//	*Wrapper_RepairChunkResponse
	//	*Wrapper_ChunkLocationsRequest
	//	*Wrapper_ChunkLocationsResponse
	Msg           isWrapper_Msg `protobuf_oneof:"msg"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Wrapper) Reset() {
	*x = Wrapper{}
	mi := &file_dfs_proto_msgTypes[37]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Wrapper) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Wrapper) ProtoMessage() {}

func (x *Wrapper) ProtoReflect() protoreflect.Message {
	mi := &file_dfs_proto_msgTypes[37]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Wrapper.ProtoReflect.Descriptor instead.
func (*Wrapper) Descriptor() ([]byte, []int) {
	return file_dfs_proto_rawDescGZIP(), []int{37}
}

func (x *Wrapper) GetMsg() isWrapper_Msg {
	if x != nil {
		return x.Msg
	}
	return nil
}

func (x *Wrapper) GetRegisterRequest() *RegisterRequest {
	if x != nil {
		if x, ok := x.Msg.(*Wrapper_RegisterRequest); ok {
			return x.RegisterRequest
		}
	}
	return nil
}

func (x *Wrapper) GetRegisterResponse() *RegisterResponse {
	if x != nil {
		if x, ok := x.Msg.(*Wrapper_RegisterResponse); ok {
			return x.RegisterResponse
		}
	}
	return nil
}

func (x *Wrapper) GetHeartbeat() *Heartbeat {
	if x != nil {
		if x, ok := x.Msg.(*Wrapper_Heartbeat); ok {
			return x.Heartbeat
		}
	}
	return nil
}

func (x *Wrapper) GetHeartbeatResponse() *HeartbeatResponse {
	if x != nil {
		if x, ok := x.Msg.(*Wrapper_HeartbeatResponse); ok {
			return x.HeartbeatResponse
		}
	}
	return nil
}

func (x *Wrapper) GetReplicateRequest() *ReplicateRequest {
	if x != nil {
		if x, ok := x.Msg.(*Wrapper_ReplicateRequest); ok {
			return x.ReplicateRequest
		}
	}
	return nil
}

func (x *Wrapper) GetStoreRequest() *StoreRequest {
	if x != nil {
		if x, ok := x.Msg.(*Wrapper_StoreRequest); ok {
			return x.StoreRequest
		}
	}
	return nil
}

func (x *Wrapper) GetStoreResponse() *StoreResponse {
	if x != nil {
		if x, ok := x.Msg.(*Wrapper_StoreResponse); ok {
			return x.StoreResponse
		}
	}
	return nil
}

func (x *Wrapper) GetRetrieveRequest() *RetrieveRequest {
	if x != nil {
		if x, ok := x.Msg.(*Wrapper_RetrieveRequest); ok {
			return x.RetrieveRequest
		}
	}
	return nil
}

func (x *Wrapper) GetRetrieveResponse() *RetrieveResponse {
	if x != nil {
		if x, ok := x.Msg.(*Wrapper_RetrieveResponse); ok {
			return x.RetrieveResponse
		}
	}
	return nil
}

func (x *Wrapper) GetStatFileRequest() *StatFileRequest {
	if x != nil {
		if x, ok := x.Msg.(*Wrapper_StatFileRequest); ok {
			return x.StatFileRequest
		}
	}
	return nil
}

func (x *Wrapper) GetStatFileResponse() *StatFileResponse {
	if x != nil {
		if x, ok := x.Msg.(*Wrapper_StatFileResponse); ok {
			return x.StatFileResponse
		}
	}
	return nil
}

func (x *Wrapper) GetGetInputSplitsRequest() *GetInputSplitsRequest {
	if x != nil {
		if x, ok := x.Msg.(*Wrapper_GetInputSplitsRequest); ok {
			return x.GetInputSplitsRequest
		}
	}
	return nil
}

func (x *Wrapper) GetGetInputSplitsResponse() *GetInputSplitsResponse {
	if x != nil {
		if x, ok := x.Msg.(*Wrapper_GetInputSplitsResponse); ok {
			return x.GetInputSplitsResponse
		}
	}
	return nil
}

func (x *Wrapper) GetDeleteRequest() *DeleteRequest {
	if x != nil {
		if x, ok := x.Msg.(*Wrapper_DeleteRequest); ok {
			return x.DeleteRequest
		}
	}
	return nil
}

func (x *Wrapper) GetDeleteResponse() *DeleteResponse {
	if x != nil {
		if x, ok := x.Msg.(*Wrapper_DeleteResponse); ok {
			return x.DeleteResponse
		}
	}
	return nil
}

func (x *Wrapper) GetListRequest() *ListRequest {
	if x != nil {
		if x, ok := x.Msg.(*Wrapper_ListRequest); ok {
			return x.ListRequest
		}
	}
	return nil
}

func (x *Wrapper) GetListResponse() *ListResponse {
	if x != nil {
		if x, ok := x.Msg.(*Wrapper_ListResponse); ok {
			return x.ListResponse
		}
	}
	return nil
}

func (x *Wrapper) GetClusterInfoRequest() *ClusterInfoRequest {
	if x != nil {
		if x, ok := x.Msg.(*Wrapper_ClusterInfoRequest); ok {
			return x.ClusterInfoRequest
		}
	}
	return nil
}

func (x *Wrapper) GetClusterInfoResponse() *ClusterInfoResponse {
	if x != nil {
		if x, ok := x.Msg.(*Wrapper_ClusterInfoResponse); ok {
			return x.ClusterInfoResponse
		}
	}
	return nil
}

func (x *Wrapper) GetStoreChunkRequest() *StoreChunkRequest {
	if x != nil {
		if x, ok := x.Msg.(*Wrapper_StoreChunkRequest); ok {
			return x.StoreChunkRequest
		}
	}
	return nil
}

func (x *Wrapper) GetStoreChunkResponse() *StoreChunkResponse {
	if x != nil {
		if x, ok := x.Msg.(*Wrapper_StoreChunkResponse); ok {
			return x.StoreChunkResponse
		}
	}
	return nil
}

func (x *Wrapper) GetRetrieveChunkRequest() *RetrieveChunkRequest {
	if x != nil {
		if x, ok := x.Msg.(*Wrapper_RetrieveChunkRequest); ok {
			return x.RetrieveChunkRequest
		}
	}
	return nil
}

func (x *Wrapper) GetRetrieveChunkResponse() *RetrieveChunkResponse {
	if x != nil {
		if x, ok := x.Msg.(*Wrapper_RetrieveChunkResponse); ok {
			return x.RetrieveChunkResponse
		}
	}
	return nil
}

func (x *Wrapper) GetReadChunkRangeRequest() *ReadChunkRangeRequest {
	if x != nil {
		if x, ok := x.Msg.(*Wrapper_ReadChunkRangeRequest); ok {
			return x.ReadChunkRangeRequest
		}
	}
	return nil
}

func (x *Wrapper) GetReadChunkRangeResponse() *ReadChunkRangeResponse {
	if x != nil {
		if x, ok := x.Msg.(*Wrapper_ReadChunkRangeResponse); ok {
			return x.ReadChunkRangeResponse
		}
	}
	return nil
}

func (x *Wrapper) GetDeleteChunkRequest() *DeleteChunkRequest {
	if x != nil {
		if x, ok := x.Msg.(*Wrapper_DeleteChunkRequest); ok {
			return x.DeleteChunkRequest
		}
	}
	return nil
}

func (x *Wrapper) GetDeleteChunkResponse() *DeleteChunkResponse {
	if x != nil {
		if x, ok := x.Msg.(*Wrapper_DeleteChunkResponse); ok {
			return x.DeleteChunkResponse
		}
	}
	return nil
}

func (x *Wrapper) GetRepairChunkRequest() *RepairChunkRequest {
	if x != nil {
		if x, ok := x.Msg.(*Wrapper_RepairChunkRequest); ok {
			return x.RepairChunkRequest
		}
	}
	return nil
}

func (x *Wrapper) GetRepairChunkResponse() *RepairChunkResponse {
	if x != nil {
		if x, ok := x.Msg.(*Wrapper_RepairChunkResponse); ok {
			return x.RepairChunkResponse
		}
	}
	return nil
}

func (x *Wrapper) GetChunkLocationsRequest() *ChunkLocationsRequest {
	if x != nil {
		if x, ok := x.Msg.(*Wrapper_ChunkLocationsRequest); ok {
			return x.ChunkLocationsRequest
		}
	}
	return nil
}

func (x *Wrapper) GetChunkLocationsResponse() *ChunkLocationsResponse {
	if x != nil {
		if x, ok := x.Msg.(*Wrapper_ChunkLocationsResponse); ok {
			return x.ChunkLocationsResponse
		}
	}
	return nil
}

type isWrapper_Msg interface {
	isWrapper_Msg()
}

type Wrapper_RegisterRequest struct {
	// Controller <-> Storage
	RegisterRequest *RegisterRequest `protobuf:"bytes,1,opt,name=register_request,json=registerRequest,proto3,oneof"`
}

type Wrapper_RegisterResponse struct {
	RegisterResponse *RegisterResponse `protobuf:"bytes,2,opt,name=register_response,json=registerResponse,proto3,oneof"`
}

type Wrapper_Heartbeat struct {
	Heartbeat *Heartbeat `protobuf:"bytes,3,opt,name=heartbeat,proto3,oneof"`
}

type Wrapper_HeartbeatResponse struct {
	HeartbeatResponse *HeartbeatResponse `protobuf:"bytes,4,opt,name=heartbeat_response,json=heartbeatResponse,proto3,oneof"`
}

type Wrapper_ReplicateRequest struct {
	ReplicateRequest *ReplicateRequest `protobuf:"bytes,5,opt,name=replicate_request,json=replicateRequest,proto3,oneof"`
}

type Wrapper_StoreRequest struct {
	// Client <-> Controller
	StoreRequest *StoreRequest `protobuf:"bytes,6,opt,name=store_request,json=storeRequest,proto3,oneof"`
}

type Wrapper_StoreResponse struct {
	StoreResponse *StoreResponse `protobuf:"bytes,7,opt,name=store_response,json=storeResponse,proto3,oneof"`
}

type Wrapper_RetrieveRequest struct {
	RetrieveRequest *RetrieveRequest `protobuf:"bytes,8,opt,name=retrieve_request,json=retrieveRequest,proto3,oneof"`
}

type Wrapper_RetrieveResponse struct {
	RetrieveResponse *RetrieveResponse `protobuf:"bytes,9,opt,name=retrieve_response,json=retrieveResponse,proto3,oneof"`
}

type Wrapper_StatFileRequest struct {
	StatFileRequest *StatFileRequest `protobuf:"bytes,10,opt,name=stat_file_request,json=statFileRequest,proto3,oneof"`
}

type Wrapper_StatFileResponse struct {
	StatFileResponse *StatFileResponse `protobuf:"bytes,11,opt,name=stat_file_response,json=statFileResponse,proto3,oneof"`
}

type Wrapper_GetInputSplitsRequest struct {
	GetInputSplitsRequest *GetInputSplitsRequest `protobuf:"bytes,12,opt,name=get_input_splits_request,json=getInputSplitsRequest,proto3,oneof"`
}

type Wrapper_GetInputSplitsResponse struct {
	GetInputSplitsResponse *GetInputSplitsResponse `protobuf:"bytes,13,opt,name=get_input_splits_response,json=getInputSplitsResponse,proto3,oneof"`
}

type Wrapper_DeleteRequest struct {
	DeleteRequest *DeleteRequest `protobuf:"bytes,14,opt,name=delete_request,json=deleteRequest,proto3,oneof"`
}

type Wrapper_DeleteResponse struct {
	DeleteResponse *DeleteResponse `protobuf:"bytes,15,opt,name=delete_response,json=deleteResponse,proto3,oneof"`
}

type Wrapper_ListRequest struct {
	ListRequest *ListRequest `protobuf:"bytes,16,opt,name=list_request,json=listRequest,proto3,oneof"`
}

type Wrapper_ListResponse struct {
	ListResponse *ListResponse `protobuf:"bytes,17,opt,name=list_response,json=listResponse,proto3,oneof"`
}

type Wrapper_ClusterInfoRequest struct {
	ClusterInfoRequest *ClusterInfoRequest `protobuf:"bytes,18,opt,name=cluster_info_request,json=clusterInfoRequest,proto3,oneof"`
}

type Wrapper_ClusterInfoResponse struct {
	ClusterInfoResponse *ClusterInfoResponse `protobuf:"bytes,19,opt,name=cluster_info_response,json=clusterInfoResponse,proto3,oneof"`
}

type Wrapper_StoreChunkRequest struct {
	// Client <-> Storage
	StoreChunkRequest *StoreChunkRequest `protobuf:"bytes,20,opt,name=store_chunk_request,json=storeChunkRequest,proto3,oneof"`
}

type Wrapper_StoreChunkResponse struct {
	StoreChunkResponse *StoreChunkResponse `protobuf:"bytes,21,opt,name=store_chunk_response,json=storeChunkResponse,proto3,oneof"`
}

type Wrapper_RetrieveChunkRequest struct {
	RetrieveChunkRequest *RetrieveChunkRequest `protobuf:"bytes,22,opt,name=retrieve_chunk_request,json=retrieveChunkRequest,proto3,oneof"`
}

type Wrapper_RetrieveChunkResponse struct {
	RetrieveChunkResponse *RetrieveChunkResponse `protobuf:"bytes,23,opt,name=retrieve_chunk_response,json=retrieveChunkResponse,proto3,oneof"`
}

type Wrapper_ReadChunkRangeRequest struct {
	ReadChunkRangeRequest *ReadChunkRangeRequest `protobuf:"bytes,24,opt,name=read_chunk_range_request,json=readChunkRangeRequest,proto3,oneof"`
}

type Wrapper_ReadChunkRangeResponse struct {
	ReadChunkRangeResponse *ReadChunkRangeResponse `protobuf:"bytes,25,opt,name=read_chunk_range_response,json=readChunkRangeResponse,proto3,oneof"`
}

type Wrapper_DeleteChunkRequest struct {
	// Controller <-> Storage
	DeleteChunkRequest *DeleteChunkRequest `protobuf:"bytes,26,opt,name=delete_chunk_request,json=deleteChunkRequest,proto3,oneof"`
}

type Wrapper_DeleteChunkResponse struct {
	DeleteChunkResponse *DeleteChunkResponse `protobuf:"bytes,27,opt,name=delete_chunk_response,json=deleteChunkResponse,proto3,oneof"`
}

type Wrapper_RepairChunkRequest struct {
	// Checksum validation
	RepairChunkRequest *RepairChunkRequest `protobuf:"bytes,28,opt,name=repair_chunk_request,json=repairChunkRequest,proto3,oneof"`
}

type Wrapper_RepairChunkResponse struct {
	RepairChunkResponse *RepairChunkResponse `protobuf:"bytes,29,opt,name=repair_chunk_response,json=repairChunkResponse,proto3,oneof"`
}

type Wrapper_ChunkLocationsRequest struct {
	ChunkLocationsRequest *ChunkLocationsRequest `protobuf:"bytes,30,opt,name=chunk_locations_request,json=chunkLocationsRequest,proto3,oneof"`
}

type Wrapper_ChunkLocationsResponse struct {
	ChunkLocationsResponse *ChunkLocationsResponse `protobuf:"bytes,31,opt,name=chunk_locations_response,json=chunkLocationsResponse,proto3,oneof"`
}

func (*Wrapper_RegisterRequest) isWrapper_Msg() {}

func (*Wrapper_RegisterResponse) isWrapper_Msg() {}

func (*Wrapper_Heartbeat) isWrapper_Msg() {}

func (*Wrapper_HeartbeatResponse) isWrapper_Msg() {}

func (*Wrapper_ReplicateRequest) isWrapper_Msg() {}

func (*Wrapper_StoreRequest) isWrapper_Msg() {}

func (*Wrapper_StoreResponse) isWrapper_Msg() {}

func (*Wrapper_RetrieveRequest) isWrapper_Msg() {}

func (*Wrapper_RetrieveResponse) isWrapper_Msg() {}

func (*Wrapper_StatFileRequest) isWrapper_Msg() {}

func (*Wrapper_StatFileResponse) isWrapper_Msg() {}

func (*Wrapper_GetInputSplitsRequest) isWrapper_Msg() {}

func (*Wrapper_GetInputSplitsResponse) isWrapper_Msg() {}

func (*Wrapper_DeleteRequest) isWrapper_Msg() {}

func (*Wrapper_DeleteResponse) isWrapper_Msg() {}

func (*Wrapper_ListRequest) isWrapper_Msg() {}

func (*Wrapper_ListResponse) isWrapper_Msg() {}

func (*Wrapper_ClusterInfoRequest) isWrapper_Msg() {}

func (*Wrapper_ClusterInfoResponse) isWrapper_Msg() {}

func (*Wrapper_StoreChunkRequest) isWrapper_Msg() {}

func (*Wrapper_StoreChunkResponse) isWrapper_Msg() {}

func (*Wrapper_RetrieveChunkRequest) isWrapper_Msg() {}

func (*Wrapper_RetrieveChunkResponse) isWrapper_Msg() {}

func (*Wrapper_ReadChunkRangeRequest) isWrapper_Msg() {}

func (*Wrapper_ReadChunkRangeResponse) isWrapper_Msg() {}

func (*Wrapper_DeleteChunkRequest) isWrapper_Msg() {}

func (*Wrapper_DeleteChunkResponse) isWrapper_Msg() {}

func (*Wrapper_RepairChunkRequest) isWrapper_Msg() {}

func (*Wrapper_RepairChunkResponse) isWrapper_Msg() {}

func (*Wrapper_ChunkLocationsRequest) isWrapper_Msg() {}

func (*Wrapper_ChunkLocationsResponse) isWrapper_Msg() {}

var File_dfs_proto protoreflect.FileDescriptor

const file_dfs_proto_rawDesc = "" +
	"\n" +
	"\tdfs.proto\"`\n" +
	"\x0fRegisterRequest\x12\x1a\n" +
	"\bhostname\x18\x01 \x01(\tR\bhostname\x12\x12\n" +
	"\x04port\x18\x02 \x01(\x05R\x04port\x12\x1d\n" +
	"\n" +
	"free_space\x18\x03 \x01(\x04R\tfreeSpace\"Q\n" +
	"\x10RegisterResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12\x17\n" +
	"\anode_id\x18\x02 \x01(\rR\x06nodeId\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\"\x8f\x01\n" +
	"\tHeartbeat\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\rR\x06nodeId\x12\x1d\n" +
	"\n" +
	"free_space\x18\x02 \x01(\x04R\tfreeSpace\x12\x1f\n" +
	"\vnum_request\x18\x03 \x01(\x04R\n" +
	"numRequest\x12)\n" +
	"\n" +
	"new_chunks\x18\x04 \x03(\v2\n" +
	".ChunkInfoR\tnewChunks\"e\n" +
	"\x11HeartbeatResponse\x12\x10\n" +
	"\x03ack\x18\x01 \x01(\bR\x03ack\x12>\n" +
	"\x11replicate_request\x18\x02 \x03(\v2\x11.ReplicateRequestR\x10replicateRequest\"s\n" +
	"\x10ReplicateRequest\x12\x19\n" +
	"\bsrc_host\x18\x01 \x01(\tR\asrcHost\x12\x19\n" +
	"\bsrc_port\x18\x02 \x01(\x05R\asrcPort\x12)\n" +
	"\n" +
	"chunk_info\x18\x03 \x01(\v2\n" +
	".ChunkInfoR\tchunkInfo\"H\n" +
	"\tChunkInfo\x12\x1a\n" +
	"\bfilename\x18\x01 \x01(\tR\bfilename\x12\x1f\n" +
	"\vchunk_index\x18\x02 \x01(\rR\n" +
	"chunkIndex\"S\n" +
	"\bNodeInfo\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\rR\x06nodeId\x12\x1a\n" +
	"\bhostname\x18\x02 \x01(\tR\bhostname\x12\x12\n" +
	"\x04port\x18\x03 \x01(\x05R\x04port\"Z\n" +
	"\fChunkMapping\x12)\n" +
	"\n" +
	"chunk_info\x18\x01 \x01(\v2\n" +
	".ChunkInfoR\tchunkInfo\x12\x1f\n" +
	"\x05nodes\x18\x02 \x03(\v2\t.NodeInfoR\x05nodes\"\x87\x01\n" +
	"\fStoreRequest\x12\x1a\n" +
	"\bfilename\x18\x01 \x01(\tR\bfilename\x12\x1f\n" +
	"\vchunk_count\x18\x02 \x01(\rR\n" +
	"chunkCount\x12\x1d\n" +
	"\n" +
	"chunk_size\x18\x03 \x01(\x04R\tchunkSize\x12\x1b\n" +
	"\tfile_size\x18\x04 \x01(\x04R\bfileSize\"h\n" +
	"\rStoreResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\x121\n" +
	"\fdestinations\x18\x03 \x03(\v2\r.ChunkMappingR\fdestinations\"-\n" +
	"\x0fRetrieveRequest\x12\x1a\n" +
	"\bfilename\x18\x01 \x01(\tR\bfilename\"e\n" +
	"\x10RetrieveResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\x12+\n" +
	"\tlocations\x18\x03 \x03(\v2\r.ChunkMappingR\tlocations\"-\n" +
	"\x0fStatFileRequest\x12\x1a\n" +
	"\bfilename\x18\x01 \x01(\tR\bfilename\"\xb1\x01\n" +
	"\x10StatFileResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\x12\x1a\n" +
	"\bfilename\x18\x03 \x01(\tR\bfilename\x12\x1b\n" +
	"\tfile_size\x18\x04 \x01(\x04R\bfileSize\x12\x1d\n" +
	"\n" +
	"chunk_size\x18\x05 \x01(\x04R\tchunkSize\x12\x1f\n" +
	"\vchunk_count\x18\x06 \x01(\rR\n" +
	"chunkCount\"\xfe\x01\n" +
	"\n" +
	"InputSplit\x12\x1f\n" +
	"\vsplit_index\x18\x01 \x01(\rR\n" +
	"splitIndex\x12\x1a\n" +
	"\bfilename\x18\x02 \x01(\tR\bfilename\x12!\n" +
	"\fstart_offset\x18\x03 \x01(\x04R\vstartOffset\x120\n" +
	"\x14end_offset_exclusive\x18\x04 \x01(\x04R\x12endOffsetExclusive\x12*\n" +
	"\x11start_line_number\x18\x05 \x01(\x04R\x0fstartLineNumber\x122\n" +
	"\x0fpreferred_nodes\x18\x06 \x03(\v2\t.NodeInfoR\x0epreferredNodes\"\x97\x01\n" +
	"\x15GetInputSplitsRequest\x12\x1a\n" +
	"\bfilename\x18\x01 \x01(\tR\bfilename\x12)\n" +
	"\n" +
	"split_mode\x18\x02 \x01(\x0e2\n" +
	".SplitModeR\tsplitMode\x127\n" +
	"\x18desired_split_size_bytes\x18\x03 \x01(\x04R\x15desiredSplitSizeBytes\"c\n" +
	"\x16GetInputSplitsResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\x12#\n" +
	"\x06splits\x18\x03 \x03(\v2\v.InputSplitR\x06splits\"+\n" +
	"\rDeleteRequest\x12\x1a\n" +
	"\bfilename\x18\x01 \x01(\tR\bfilename\"6\n" +
	"\x0eDeleteResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"\r\n" +
	"\vListRequest\"d\n" +
	"\bFileInfo\x12\x1a\n" +
	"\bfilename\x18\x01 \x01(\tR\bfilename\x12\x1b\n" +
	"\tfile_size\x18\x02 \x01(\x04R\bfileSize\x12\x1f\n" +
	"\vchunk_count\x18\x03 \x01(\rR\n" +
	"chunkCount\"U\n" +
	"\fListResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\x12\x1f\n" +
	"\x05files\x18\x03 \x03(\v2\t.FileInfoR\x05files\"\x14\n" +
	"\x12ClusterInfoRequest\"u\n" +
	"\tNodeStats\x12&\n" +
	"\tnode_info\x18\x01 \x01(\v2\t.NodeInfoR\bnodeInfo\x12\x1d\n" +
	"\n" +
	"free_space\x18\x02 \x01(\x04R\tfreeSpace\x12!\n" +
	"\fnum_requests\x18\x03 \x01(\x04R\vnumRequests\"\x91\x01\n" +
	"\x13ClusterInfoResponse\x12)\n" +
	"\n" +
	"node_stats\x18\x01 \x03(\v2\n" +
	".NodeStatsR\tnodeStats\x12(\n" +
	"\x10total_free_space\x18\x02 \x01(\x04R\x0etotalFreeSpace\x12%\n" +
	"\x0etotal_requests\x18\x03 \x01(\x04R\rtotalRequests\"\xa0\x01\n" +
	"\x11StoreChunkRequest\x12)\n" +
	"\n" +
	"chunk_info\x18\x01 \x01(\v2\n" +
	".ChunkInfoR\tchunkInfo\x12\x1d\n" +
	"\n" +
	"chunk_data\x18\x02 \x01(\fR\tchunkData\x12\x1a\n" +
	"\bchecksum\x18\x03 \x01(\fR\bchecksum\x12%\n" +
	"\bpipeline\x18\x04 \x03(\v2\t.NodeInfoR\bpipeline\"e\n" +
	"\x12StoreChunkResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\x12)\n" +
	"\n" +
	"chunk_info\x18\x03 \x01(\v2\n" +
	".ChunkInfoR\tchunkInfo\"q\n" +
	"\x14RetrieveChunkRequest\x12)\n" +
	"\n" +
	"chunk_info\x18\x01 \x01(\v2\n" +
	".ChunkInfoR\tchunkInfo\x12.\n" +
	"\rreplica_hints\x18\x02 \x03(\v2\t.NodeInfoR\freplicaHints\"\\\n" +
	"\x15RetrieveChunkResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\x12\x1d\n" +
	"\n" +
	"chunk_data\x18\x03 \x01(\fR\tchunkData\"}\n" +
	"\x15ReadChunkRangeRequest\x12)\n" +
	"\n" +
	"chunk_info\x18\x01 \x01(\v2\n" +
	".ChunkInfoR\tchunkInfo\x12!\n" +
	"\fchunk_offset\x18\x02 \x01(\x04R\vchunkOffset\x12\x16\n" +
	"\x06length\x18\x03 \x01(\x04R\x06length\"\x88\x01\n" +
	"\x16ReadChunkRangeResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\x12)\n" +
	"\n" +
	"chunk_info\x18\x03 \x01(\v2\n" +
	".ChunkInfoR\tchunkInfo\x12\x1d\n" +
	"\n" +
	"chunk_data\x18\x04 \x01(\fR\tchunkData\"?\n" +
	"\x12DeleteChunkRequest\x12)\n" +
	"\n" +
	"chunk_info\x18\x01 \x01(\v2\n" +
	".ChunkInfoR\tchunkInfo\"f\n" +
	"\x13DeleteChunkResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\x12)\n" +
	"\n" +
	"chunk_info\x18\x03 \x01(\v2\n" +
	".ChunkInfoR\tchunkInfo\"?\n" +
	"\x12RepairChunkRequest\x12)\n" +
	"\n" +
	"chunk_info\x18\x01 \x01(\v2\n" +
	".ChunkInfoR\tchunkInfo\"\x85\x01\n" +
	"\x13RepairChunkResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\x12)\n" +
	"\n" +
	"chunk_info\x18\x03 \x01(\v2\n" +
	".ChunkInfoR\tchunkInfo\x12\x1d\n" +
	"\n" +
	"chunk_data\x18\x04 \x01(\fR\tchunkData\"B\n" +
	"\x15ChunkLocationsRequest\x12)\n" +
	"\n" +
	"chunk_info\x18\x01 \x01(\v2\n" +
	".ChunkInfoR\tchunkInfo\"\x8a\x01\n" +
	"\x16ChunkLocationsResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\x12)\n" +
	"\n" +
	"chunk_info\x18\x03 \x01(\v2\n" +
	".ChunkInfoR\tchunkInfo\x12\x1f\n" +
	"\x05nodes\x18\x04 \x03(\v2\t.NodeInfoR\x05nodes\"\xfd\x10\n" +
	"\aWrapper\x12=\n" +
	"\x10register_request\x18\x01 \x01(\v2\x10.RegisterRequestH\x00R\x0fregisterRequest\x12@\n" +
	"\x11register_response\x18\x02 \x01(\v2\x11.RegisterResponseH\x00R\x10registerResponse\x12*\n" +
	"\theartbeat\x18\x03 \x01(\v2\n" +
	".HeartbeatH\x00R\theartbeat\x12C\n" +
	"\x12heartbeat_response\x18\x04 \x01(\v2\x12.HeartbeatResponseH\x00R\x11heartbeatResponse\x12@\n" +
	"\x11replicate_request\x18\x05 \x01(\v2\x11.ReplicateRequestH\x00R\x10replicateRequest\x124\n" +
	"\rstore_request\x18\x06 \x01(\v2\r.StoreRequestH\x00R\fstoreRequest\x127\n" +
	"\x0estore_response\x18\a \x01(\v2\x0e.StoreResponseH\x00R\rstoreResponse\x12=\n" +
	"\x10retrieve_request\x18\b \x01(\v2\x10.RetrieveRequestH\x00R\x0fretrieveRequest\x12@\n" +
	"\x11retrieve_response\x18\t \x01(\v2\x11.RetrieveResponseH\x00R\x10retrieveResponse\x12>\n" +
	"\x11stat_file_request\x18\n" +
	" \x01(\v2\x10.StatFileRequestH\x00R\x0fstatFileRequest\x12A\n" +
	"\x12stat_file_response\x18\v \x01(\v2\x11.StatFileResponseH\x00R\x10statFileResponse\x12Q\n" +
	"\x18get_input_splits_request\x18\f \x01(\v2\x16.GetInputSplitsRequestH\x00R\x15getInputSplitsRequest\x12T\n" +
	"\x19get_input_splits_response\x18\r \x01(\v2\x17.GetInputSplitsResponseH\x00R\x16getInputSplitsResponse\x127\n" +
	"\x0edelete_request\x18\x0e \x01(\v2\x0e.DeleteRequestH\x00R\rdeleteRequest\x12:\n" +
	"\x0fdelete_response\x18\x0f \x01(\v2\x0f.DeleteResponseH\x00R\x0edeleteResponse\x121\n" +
	"\flist_request\x18\x10 \x01(\v2\f.ListRequestH\x00R\vlistRequest\x124\n" +
	"\rlist_response\x18\x11 \x01(\v2\r.ListResponseH\x00R\flistResponse\x12G\n" +
	"\x14cluster_info_request\x18\x12 \x01(\v2\x13.ClusterInfoRequestH\x00R\x12clusterInfoRequest\x12J\n" +
	"\x15cluster_info_response\x18\x13 \x01(\v2\x14.ClusterInfoResponseH\x00R\x13clusterInfoResponse\x12D\n" +
	"\x13store_chunk_request\x18\x14 \x01(\v2\x12.StoreChunkRequestH\x00R\x11storeChunkRequest\x12G\n" +
	"\x14store_chunk_response\x18\x15 \x01(\v2\x13.StoreChunkResponseH\x00R\x12storeChunkResponse\x12M\n" +
	"\x16retrieve_chunk_request\x18\x16 \x01(\v2\x15.RetrieveChunkRequestH\x00R\x14retrieveChunkRequest\x12P\n" +
	"\x17retrieve_chunk_response\x18\x17 \x01(\v2\x16.RetrieveChunkResponseH\x00R\x15retrieveChunkResponse\x12Q\n" +
	"\x18read_chunk_range_request\x18\x18 \x01(\v2\x16.ReadChunkRangeRequestH\x00R\x15readChunkRangeRequest\x12T\n" +
	"\x19read_chunk_range_response\x18\x19 \x01(\v2\x17.ReadChunkRangeResponseH\x00R\x16readChunkRangeResponse\x12G\n" +
	"\x14delete_chunk_request\x18\x1a \x01(\v2\x13.DeleteChunkRequestH\x00R\x12deleteChunkRequest\x12J\n" +
	"\x15delete_chunk_response\x18\x1b \x01(\v2\x14.DeleteChunkResponseH\x00R\x13deleteChunkResponse\x12G\n" +
	"\x14repair_chunk_request\x18\x1c \x01(\v2\x13.RepairChunkRequestH\x00R\x12repairChunkRequest\x12J\n" +
	"\x15repair_chunk_response\x18\x1d \x01(\v2\x14.RepairChunkResponseH\x00R\x13repairChunkResponse\x12P\n" +
	"\x17chunk_locations_request\x18\x1e \x01(\v2\x16.ChunkLocationsRequestH\x00R\x15chunkLocationsRequest\x12S\n" +
	"\x18chunk_locations_response\x18\x1f \x01(\v2\x17.ChunkLocationsResponseH\x00R\x16chunkLocationsResponseB\x05\n" +
	"\x03msg*J\n" +
	"\tSplitMode\x12\x1a\n" +
	"\x16SPLIT_MODE_UNSPECIFIED\x10\x00\x12\x0e\n" +
	"\n" +
	"TEXT_LINES\x10\x01\x12\x11\n" +
	"\rBINARY_CHUNKS\x10\x02B@Z>github.com/erwannd/p1-distributed-filesystem/messages;messagesb\x06proto3"

var (
	file_dfs_proto_rawDescOnce sync.Once
	file_dfs_proto_rawDescData []byte
)

func file_dfs_proto_rawDescGZIP() []byte {
	file_dfs_proto_rawDescOnce.Do(func() {
		file_dfs_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_dfs_proto_rawDesc), len(file_dfs_proto_rawDesc)))
	})
	return file_dfs_proto_rawDescData
}

var file_dfs_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_dfs_proto_msgTypes = make([]protoimpl.MessageInfo, 38)
var file_dfs_proto_goTypes = []any{
	(SplitMode)(0),                 // 0: SplitMode
	(*RegisterRequest)(nil),        // 1: RegisterRequest
	(*RegisterResponse)(nil),       // 2: RegisterResponse
	(*Heartbeat)(nil),              // 3: Heartbeat
	(*HeartbeatResponse)(nil),      // 4: HeartbeatResponse
	(*ReplicateRequest)(nil),       // 5: ReplicateRequest
	(*ChunkInfo)(nil),              // 6: ChunkInfo
	(*NodeInfo)(nil),               // 7: NodeInfo
	(*ChunkMapping)(nil),           // 8: ChunkMapping
	(*StoreRequest)(nil),           // 9: StoreRequest
	(*StoreResponse)(nil),          // 10: StoreResponse
	(*RetrieveRequest)(nil),        // 11: RetrieveRequest
	(*RetrieveResponse)(nil),       // 12: RetrieveResponse
	(*StatFileRequest)(nil),        // 13: StatFileRequest
	(*StatFileResponse)(nil),       // 14: StatFileResponse
	(*InputSplit)(nil),             // 15: InputSplit
	(*GetInputSplitsRequest)(nil),  // 16: GetInputSplitsRequest
	(*GetInputSplitsResponse)(nil), // 17: GetInputSplitsResponse
	(*DeleteRequest)(nil),          // 18: DeleteRequest
	(*DeleteResponse)(nil),         // 19: DeleteResponse
	(*ListRequest)(nil),            // 20: ListRequest
	(*FileInfo)(nil),               // 21: FileInfo
	(*ListResponse)(nil),           // 22: ListResponse
	(*ClusterInfoRequest)(nil),     // 23: ClusterInfoRequest
	(*NodeStats)(nil),              // 24: NodeStats
	(*ClusterInfoResponse)(nil),    // 25: ClusterInfoResponse
	(*StoreChunkRequest)(nil),      // 26: StoreChunkRequest
	(*StoreChunkResponse)(nil),     // 27: StoreChunkResponse
	(*RetrieveChunkRequest)(nil),   // 28: RetrieveChunkRequest
	(*RetrieveChunkResponse)(nil),  // 29: RetrieveChunkResponse
	(*ReadChunkRangeRequest)(nil),  // 30: ReadChunkRangeRequest
	(*ReadChunkRangeResponse)(nil), // 31: ReadChunkRangeResponse
	(*DeleteChunkRequest)(nil),     // 32: DeleteChunkRequest
	(*DeleteChunkResponse)(nil),    // 33: DeleteChunkResponse
	(*RepairChunkRequest)(nil),     // 34: RepairChunkRequest
	(*RepairChunkResponse)(nil),    // 35: RepairChunkResponse
	(*ChunkLocationsRequest)(nil),  // 36: ChunkLocationsRequest
	(*ChunkLocationsResponse)(nil), // 37: ChunkLocationsResponse
	(*Wrapper)(nil),                // 38: Wrapper
}
var file_dfs_proto_depIdxs = []int32{
	6,  // 0: Heartbeat.new_chunks:type_name -> ChunkInfo
	5,  // 1: HeartbeatResponse.replicate_request:type_name -> ReplicateRequest
	6,  // 2: ReplicateRequest.chunk_info:type_name -> ChunkInfo
	6,  // 3: ChunkMapping.chunk_info:type_name -> ChunkInfo
	7,  // 4: ChunkMapping.nodes:type_name -> NodeInfo
	8,  // 5: StoreResponse.destinations:type_name -> ChunkMapping
	8,  // 6: RetrieveResponse.locations:type_name -> ChunkMapping
	7,  // 7: InputSplit.preferred_nodes:type_name -> NodeInfo
	0,  // 8: GetInputSplitsRequest.split_mode:type_name -> SplitMode
	15, // 9: GetInputSplitsResponse.splits:type_name -> InputSplit
	21, // 10: ListResponse.files:type_name -> FileInfo
	7,  // 11: NodeStats.node_info:type_name -> NodeInfo
	24, // 12: ClusterInfoResponse.node_stats:type_name -> NodeStats
	6,  // 13: StoreChunkRequest.chunk_info:type_name -> ChunkInfo
	7,  // 14: StoreChunkRequest.pipeline:type_name -> NodeInfo
	6,  // 15: StoreChunkResponse.chunk_info:type_name -> ChunkInfo
	6,  // 16: RetrieveChunkRequest.chunk_info:type_name -> ChunkInfo
	7,  // 17: RetrieveChunkRequest.replica_hints:type_name -> NodeInfo
	6,  // 18: ReadChunkRangeRequest.chunk_info:type_name -> ChunkInfo
	6,  // 19: ReadChunkRangeResponse.chunk_info:type_name -> ChunkInfo
	6,  // 20: DeleteChunkRequest.chunk_info:type_name -> ChunkInfo
	6,  // 21: DeleteChunkResponse.chunk_info:type_name -> ChunkInfo
	6,  // 22: RepairChunkRequest.chunk_info:type_name -> ChunkInfo
	6,  // 23: RepairChunkResponse.chunk_info:type_name -> ChunkInfo
	6,  // 24: ChunkLocationsRequest.chunk_info:type_name -> ChunkInfo
	6,  // 25: ChunkLocationsResponse.chunk_info:type_name -> ChunkInfo
	7,  // 26: ChunkLocationsResponse.nodes:type_name -> NodeInfo
	1,  // 27: Wrapper.register_request:type_name -> RegisterRequest
	2,  // 28: Wrapper.register_response:type_name -> RegisterResponse
	3,  // 29: Wrapper.heartbeat:type_name -> Heartbeat
	4,  // 30: Wrapper.heartbeat_response:type_name -> HeartbeatResponse
	5,  // 31: Wrapper.replicate_request:type_name -> ReplicateRequest
	9,  // 32: Wrapper.store_request:type_name -> StoreRequest
	10, // 33: Wrapper.store_response:type_name -> StoreResponse
	11, // 34: Wrapper.retrieve_request:type_name -> RetrieveRequest
	12, // 35: Wrapper.retrieve_response:type_name -> RetrieveResponse
	13, // 36: Wrapper.stat_file_request:type_name -> StatFileRequest
	14, // 37: Wrapper.stat_file_response:type_name -> StatFileResponse
	16, // 38: Wrapper.get_input_splits_request:type_name -> GetInputSplitsRequest
	17, // 39: Wrapper.get_input_splits_response:type_name -> GetInputSplitsResponse
	18, // 40: Wrapper.delete_request:type_name -> DeleteRequest
	19, // 41: Wrapper.delete_response:type_name -> DeleteResponse
	20, // 42: Wrapper.list_request:type_name -> ListRequest
	22, // 43: Wrapper.list_response:type_name -> ListResponse
	23, // 44: Wrapper.cluster_info_request:type_name -> ClusterInfoRequest
	25, // 45: Wrapper.cluster_info_response:type_name -> ClusterInfoResponse
	26, // 46: Wrapper.store_chunk_request:type_name -> StoreChunkRequest
	27, // 47: Wrapper.store_chunk_response:type_name -> StoreChunkResponse
	28, // 48: Wrapper.retrieve_chunk_request:type_name -> RetrieveChunkRequest
	29, // 49: Wrapper.retrieve_chunk_response:type_name -> RetrieveChunkResponse
	30, // 50: Wrapper.read_chunk_range_request:type_name -> ReadChunkRangeRequest
	31, // 51: Wrapper.read_chunk_range_response:type_name -> ReadChunkRangeResponse
	32, // 52: Wrapper.delete_chunk_request:type_name -> DeleteChunkRequest
	33, // 53: Wrapper.delete_chunk_response:type_name -> DeleteChunkResponse
	34, // 54: Wrapper.repair_chunk_request:type_name -> RepairChunkRequest
	35, // 55: Wrapper.repair_chunk_response:type_name -> RepairChunkResponse
	36, // 56: Wrapper.chunk_locations_request:type_name -> ChunkLocationsRequest
	37, // 57: Wrapper.chunk_locations_response:type_name -> ChunkLocationsResponse
	58, // [58:58] is the sub-list for method output_type
	58, // [58:58] is the sub-list for method input_type
	58, // [58:58] is the sub-list for extension type_name
	58, // [58:58] is the sub-list for extension extendee
	0,  // [0:58] is the sub-list for field type_name
}

func init() { file_dfs_proto_init() }
func file_dfs_proto_init() {
	if File_dfs_proto != nil {
		return
	}
	file_dfs_proto_msgTypes[37].OneofWrappers = []any{
		(*Wrapper_RegisterRequest)(nil),
		(*Wrapper_RegisterResponse)(nil),
		(*Wrapper_Heartbeat)(nil),
		(*Wrapper_HeartbeatResponse)(nil),
		(*Wrapper_ReplicateRequest)(nil),
		(*Wrapper_StoreRequest)(nil),
		(*Wrapper_StoreResponse)(nil),
		(*Wrapper_RetrieveRequest)(nil),
		(*Wrapper_RetrieveResponse)(nil),
		(*Wrapper_StatFileRequest)(nil),
		(*Wrapper_StatFileResponse)(nil),
		(*Wrapper_GetInputSplitsRequest)(nil),
		(*Wrapper_GetInputSplitsResponse)(nil),
		(*Wrapper_DeleteRequest)(nil),
		(*Wrapper_DeleteResponse)(nil),
		(*Wrapper_ListRequest)(nil),
		(*Wrapper_ListResponse)(nil),
		(*Wrapper_ClusterInfoRequest)(nil),
		(*Wrapper_ClusterInfoResponse)(nil),
		(*Wrapper_StoreChunkRequest)(nil),
		(*Wrapper_StoreChunkResponse)(nil),
		(*Wrapper_RetrieveChunkRequest)(nil),
		(*Wrapper_RetrieveChunkResponse)(nil),
		(*Wrapper_ReadChunkRangeRequest)(nil),
		(*Wrapper_ReadChunkRangeResponse)(nil),
		(*Wrapper_DeleteChunkRequest)(nil),
		(*Wrapper_DeleteChunkResponse)(nil),
		(*Wrapper_RepairChunkRequest)(nil),
		(*Wrapper_RepairChunkResponse)(nil),
		(*Wrapper_ChunkLocationsRequest)(nil),
		(*Wrapper_ChunkLocationsResponse)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_dfs_proto_rawDesc), len(file_dfs_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   38,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_dfs_proto_goTypes,
		DependencyIndexes: file_dfs_proto_depIdxs,
		EnumInfos:         file_dfs_proto_enumTypes,
		MessageInfos:      file_dfs_proto_msgTypes,
	}.Build()
	File_dfs_proto = out.File
	file_dfs_proto_goTypes = nil
	file_dfs_proto_depIdxs = nil
}
