// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: dfs.proto

package messages

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Storage -> Controller
// Send when a Storage node just started
type RegisterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hostname      string                 `protobuf:"bytes,1,opt,name=hostname,proto3" json:"hostname,omitempty"`                     // hostname or IP
	Port          int32                  `protobuf:"varint,2,opt,name=port,proto3" json:"port,omitempty"`                            // listening port
	FreeSpace     uint64                 `protobuf:"varint,3,opt,name=free_space,json=freeSpace,proto3" json:"free_space,omitempty"` // available disk space (bytes)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterRequest) Reset() {
	*x = RegisterRequest{}
	mi := &file_dfs_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRequest) ProtoMessage() {}

func (x *RegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dfs_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRequest.ProtoReflect.Descriptor instead.
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return file_dfs_proto_rawDescGZIP(), []int{0}
}

func (x *RegisterRequest) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *RegisterRequest) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *RegisterRequest) GetFreeSpace() uint64 {
	if x != nil {
		return x.FreeSpace
	}
	return 0
}

// Controller -> Storage
type RegisterResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	NodeId        uint32                 `protobuf:"varint,2,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"` // unique ID for this node
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`                  // empty if ok=True otherwise error message
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterResponse) Reset() {
	*x = RegisterResponse{}
	mi := &file_dfs_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterResponse) ProtoMessage() {}

func (x *RegisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dfs_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterResponse.ProtoReflect.Descriptor instead.
func (*RegisterResponse) Descriptor() ([]byte, []int) {
	return file_dfs_proto_rawDescGZIP(), []int{1}
}

func (x *RegisterResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *RegisterResponse) GetNodeId() uint32 {
	if x != nil {
		return x.NodeId
	}
	return 0
}

func (x *RegisterResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// Storage -> Controller
// Send every 5 seconds
// Piggyback replication response if Controller made a replication request
type Heartbeat struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        uint32                 `protobuf:"varint,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	FreeSpace     uint64                 `protobuf:"varint,2,opt,name=free_space,json=freeSpace,proto3" json:"free_space,omitempty"`    // free disk space (bytes)
	NumRequest    uint64                 `protobuf:"varint,3,opt,name=num_request,json=numRequest,proto3" json:"num_request,omitempty"` // number of request handled
	NewChunks     []*ChunkInfo           `protobuf:"bytes,4,rep,name=new_chunks,json=newChunks,proto3" json:"new_chunks,omitempty"`     // ack that a replication request is successful
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Heartbeat) Reset() {
	*x = Heartbeat{}
	mi := &file_dfs_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Heartbeat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Heartbeat) ProtoMessage() {}

func (x *Heartbeat) ProtoReflect() protoreflect.Message {
	mi := &file_dfs_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Heartbeat.ProtoReflect.Descriptor instead.
func (*Heartbeat) Descriptor() ([]byte, []int) {
	return file_dfs_proto_rawDescGZIP(), []int{2}
}

func (x *Heartbeat) GetNodeId() uint32 {
	if x != nil {
		return x.NodeId
	}
	return 0
}

func (x *Heartbeat) GetFreeSpace() uint64 {
	if x != nil {
		return x.FreeSpace
	}
	return 0
}

func (x *Heartbeat) GetNumRequest() uint64 {
	if x != nil {
		return x.NumRequest
	}
	return 0
}

func (x *Heartbeat) GetNewChunks() []*ChunkInfo {
	if x != nil {
		return x.NewChunks
	}
	return nil
}

// Controller -> Storage
// Piggback replication request, if a node failed
type HeartbeatResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Ack              bool                   `protobuf:"varint,1,opt,name=ack,proto3" json:"ack,omitempty"`
	ReplicateRequest []*ReplicateRequest    `protobuf:"bytes,2,rep,name=replicate_request,json=replicateRequest,proto3" json:"replicate_request,omitempty"` // maybe carry replication request here?
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *HeartbeatResponse) Reset() {
	*x = HeartbeatResponse{}
	mi := &file_dfs_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatResponse) ProtoMessage() {}

func (x *HeartbeatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dfs_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatResponse.ProtoReflect.Descriptor instead.
func (*HeartbeatResponse) Descriptor() ([]byte, []int) {
	return file_dfs_proto_rawDescGZIP(), []int{3}
}

func (x *HeartbeatResponse) GetAck() bool {
	if x != nil {
		return x.Ack
	}
	return false
}

func (x *HeartbeatResponse) GetReplicateRequest() []*ReplicateRequest {
	if x != nil {
		return x.ReplicateRequest
	}
	return nil
}

// Controller -> Storage
type ReplicateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SrcHost       string                 `protobuf:"bytes,1,opt,name=src_host,json=srcHost,proto3" json:"src_host,omitempty"`  // host to replicate chunk from
	SrcPort       int32                  `protobuf:"varint,2,opt,name=src_port,json=srcPort,proto3" json:"src_port,omitempty"` // port the host is listening on
	ChunkInfo     *ChunkInfo             `protobuf:"bytes,3,opt,name=chunk_info,json=chunkInfo,proto3" json:"chunk_info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReplicateRequest) Reset() {
	*x = ReplicateRequest{}
	mi := &file_dfs_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReplicateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplicateRequest) ProtoMessage() {}

func (x *ReplicateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dfs_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReplicateRequest.ProtoReflect.Descriptor instead.
func (*ReplicateRequest) Descriptor() ([]byte, []int) {
	return file_dfs_proto_rawDescGZIP(), []int{4}
}

func (x *ReplicateRequest) GetSrcHost() string {
	if x != nil {
		return x.SrcHost
	}
	return ""
}

func (x *ReplicateRequest) GetSrcPort() int32 {
	if x != nil {
		return x.SrcPort
	}
	return 0
}

func (x *ReplicateRequest) GetChunkInfo() *ChunkInfo {
	if x != nil {
		return x.ChunkInfo
	}
	return nil
}

// Represents a chunk of a file
type ChunkInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Filename      string                 `protobuf:"bytes,1,opt,name=filename,proto3" json:"filename,omitempty"`
	ChunkIndex    uint32                 `protobuf:"varint,2,opt,name=chunk_index,json=chunkIndex,proto3" json:"chunk_index,omitempty"` // chunk number
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChunkInfo) Reset() {
	*x = ChunkInfo{}
	mi := &file_dfs_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChunkInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChunkInfo) ProtoMessage() {}

func (x *ChunkInfo) ProtoReflect() protoreflect.Message {
	mi := &file_dfs_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChunkInfo.ProtoReflect.Descriptor instead.
func (*ChunkInfo) Descriptor() ([]byte, []int) {
	return file_dfs_proto_rawDescGZIP(), []int{5}
}

func (x *ChunkInfo) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *ChunkInfo) GetChunkIndex() uint32 {
	if x != nil {
		return x.ChunkIndex
	}
	return 0
}

// Represents a storage node's address
type NodeInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        uint32                 `protobuf:"varint,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Hostname      string                 `protobuf:"bytes,2,opt,name=hostname,proto3" json:"hostname,omitempty"`
	Port          int32                  `protobuf:"varint,3,opt,name=port,proto3" json:"port,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeInfo) Reset() {
	*x = NodeInfo{}
	mi := &file_dfs_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeInfo) ProtoMessage() {}

func (x *NodeInfo) ProtoReflect() protoreflect.Message {
	mi := &file_dfs_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeInfo.ProtoReflect.Descriptor instead.
func (*NodeInfo) Descriptor() ([]byte, []int) {
	return file_dfs_proto_rawDescGZIP(), []int{6}
}

func (x *NodeInfo) GetNodeId() uint32 {
	if x != nil {
		return x.NodeId
	}
	return 0
}

func (x *NodeInfo) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *NodeInfo) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

// Represents where to send a specific chunk
type ChunkMapping struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChunkInfo     *ChunkInfo             `protobuf:"bytes,1,opt,name=chunk_info,json=chunkInfo,proto3" json:"chunk_info,omitempty"` // which chunk
	Nodes         []*NodeInfo            `protobuf:"bytes,2,rep,name=nodes,proto3" json:"nodes,omitempty"`                          // locations of primary & replicas (e.g. [A, B, C])
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChunkMapping) Reset() {
	*x = ChunkMapping{}
	mi := &file_dfs_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChunkMapping) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChunkMapping) ProtoMessage() {}

func (x *ChunkMapping) ProtoReflect() protoreflect.Message {
	mi := &file_dfs_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChunkMapping.ProtoReflect.Descriptor instead.
func (*ChunkMapping) Descriptor() ([]byte, []int) {
	return file_dfs_proto_rawDescGZIP(), []int{7}
}

func (x *ChunkMapping) GetChunkInfo() *ChunkInfo {
	if x != nil {
		return x.ChunkInfo
	}
	return nil
}

func (x *ChunkMapping) GetNodes() []*NodeInfo {
	if x != nil {
		return x.Nodes
	}
	return nil
}

// Client -> Controller
type StoreRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Filename      string                 `protobuf:"bytes,1,opt,name=filename,proto3" json:"filename,omitempty"`
	ChunkCount    uint32                 `protobuf:"varint,2,opt,name=chunk_count,json=chunkCount,proto3" json:"chunk_count,omitempty"`
	ChunkSize     uint64                 `protobuf:"varint,3,opt,name=chunk_size,json=chunkSize,proto3" json:"chunk_size,omitempty"` // to be consistent with freespace in Heartbeat, also uint64
	FileSize      uint64                 `protobuf:"varint,4,opt,name=file_size,json=fileSize,proto3" json:"file_size,omitempty"`    // total file size
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StoreRequest) Reset() {
	*x = StoreRequest{}
	mi := &file_dfs_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StoreRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StoreRequest) ProtoMessage() {}

func (x *StoreRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dfs_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StoreRequest.ProtoReflect.Descriptor instead.
func (*StoreRequest) Descriptor() ([]byte, []int) {
	return file_dfs_proto_rawDescGZIP(), []int{8}
}

func (x *StoreRequest) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *StoreRequest) GetChunkCount() uint32 {
	if x != nil {
		return x.ChunkCount
	}
	return 0
}

func (x *StoreRequest) GetChunkSize() uint64 {
	if x != nil {
		return x.ChunkSize
	}
	return 0
}

func (x *StoreRequest) GetFileSize() uint64 {
	if x != nil {
		return x.FileSize
	}
	return 0
}

// Controller -> Client
type StoreResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"` // empty if ok=true
	Destinations  []*ChunkMapping        `protobuf:"bytes,3,rep,name=destinations,proto3" json:"destinations,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StoreResponse) Reset() {
	*x = StoreResponse{}
	mi := &file_dfs_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StoreResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StoreResponse) ProtoMessage() {}

func (x *StoreResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dfs_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StoreResponse.ProtoReflect.Descriptor instead.
func (*StoreResponse) Descriptor() ([]byte, []int) {
	return file_dfs_proto_rawDescGZIP(), []int{9}
}

func (x *StoreResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *StoreResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *StoreResponse) GetDestinations() []*ChunkMapping {
	if x != nil {
		return x.Destinations
	}
	return nil
}

// Client -> Controller
type RetrieveRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Filename      string                 `protobuf:"bytes,1,opt,name=filename,proto3" json:"filename,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RetrieveRequest) Reset() {
	*x = RetrieveRequest{}
	mi := &file_dfs_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RetrieveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RetrieveRequest) ProtoMessage() {}

func (x *RetrieveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dfs_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RetrieveRequest.ProtoReflect.Descriptor instead.
func (*RetrieveRequest) Descriptor() ([]byte, []int) {
	return file_dfs_proto_rawDescGZIP(), []int{10}
}

func (x *RetrieveRequest) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

// Controller -> Client
type RetrieveResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"` // empty if ok=true
	Locations     []*ChunkMapping        `protobuf:"bytes,3,rep,name=locations,proto3" json:"locations,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RetrieveResponse) Reset() {
	*x = RetrieveResponse{}
	mi := &file_dfs_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RetrieveResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RetrieveResponse) ProtoMessage() {}

func (x *RetrieveResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dfs_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RetrieveResponse.ProtoReflect.Descriptor instead.
func (*RetrieveResponse) Descriptor() ([]byte, []int) {
	return file_dfs_proto_rawDescGZIP(), []int{11}
}

func (x *RetrieveResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *RetrieveResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *RetrieveResponse) GetLocations() []*ChunkMapping {
	if x != nil {
		return x.Locations
	}
	return nil
}

// Client -> Controller
type DeleteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Filename      string                 `protobuf:"bytes,1,opt,name=filename,proto3" json:"filename,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteRequest) Reset() {
	*x = DeleteRequest{}
	mi := &file_dfs_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRequest) ProtoMessage() {}

func (x *DeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dfs_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRequest.ProtoReflect.Descriptor instead.
func (*DeleteRequest) Descriptor() ([]byte, []int) {
	return file_dfs_proto_rawDescGZIP(), []int{12}
}

func (x *DeleteRequest) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

// Controller -> Client
type DeleteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`      // success or fail
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"` // empty if ok=true
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteResponse) Reset() {
	*x = DeleteResponse{}
	mi := &file_dfs_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteResponse) ProtoMessage() {}

func (x *DeleteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dfs_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteResponse.ProtoReflect.Descriptor instead.
func (*DeleteResponse) Descriptor() ([]byte, []int) {
	return file_dfs_proto_rawDescGZIP(), []int{13}
}

func (x *DeleteResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *DeleteResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// Client -> Controller
// List all stored files
type ListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRequest) Reset() {
	*x = ListRequest{}
	mi := &file_dfs_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRequest) ProtoMessage() {}

func (x *ListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dfs_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRequest.ProtoReflect.Descriptor instead.
func (*ListRequest) Descriptor() ([]byte, []int) {
	return file_dfs_proto_rawDescGZIP(), []int{14}
}

// Represents a file in the system
type FileInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Filename      string                 `protobuf:"bytes,1,opt,name=filename,proto3" json:"filename,omitempty"`
	FileSize      uint64                 `protobuf:"varint,2,opt,name=file_size,json=fileSize,proto3" json:"file_size,omitempty"`
	ChunkCount    uint32                 `protobuf:"varint,3,opt,name=chunk_count,json=chunkCount,proto3" json:"chunk_count,omitempty"` // how many chunks does this file have
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileInfo) Reset() {
	*x = FileInfo{}
	mi := &file_dfs_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileInfo) ProtoMessage() {}

func (x *FileInfo) ProtoReflect() protoreflect.Message {
	mi := &file_dfs_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileInfo.ProtoReflect.Descriptor instead.
func (*FileInfo) Descriptor() ([]byte, []int) {
	return file_dfs_proto_rawDescGZIP(), []int{15}
}

func (x *FileInfo) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *FileInfo) GetFileSize() uint64 {
	if x != nil {
		return x.FileSize
	}
	return 0
}

func (x *FileInfo) GetChunkCount() uint32 {
	if x != nil {
		return x.ChunkCount
	}
	return 0
}

// Controller -> Client
type ListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	Files         []*FileInfo            `protobuf:"bytes,3,rep,name=files,proto3" json:"files,omitempty"` // empty if no files stored
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListResponse) Reset() {
	*x = ListResponse{}
	mi := &file_dfs_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListResponse) ProtoMessage() {}

func (x *ListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dfs_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListResponse.ProtoReflect.Descriptor instead.
func (*ListResponse) Descriptor() ([]byte, []int) {
	return file_dfs_proto_rawDescGZIP(), []int{16}
}

func (x *ListResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *ListResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *ListResponse) GetFiles() []*FileInfo {
	if x != nil {
		return x.Files
	}
	return nil
}

// Client -> Controller
// Request for node list + disk space + request counts
type ClusterInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClusterInfoRequest) Reset() {
	*x = ClusterInfoRequest{}
	mi := &file_dfs_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClusterInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClusterInfoRequest) ProtoMessage() {}

func (x *ClusterInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dfs_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClusterInfoRequest.ProtoReflect.Descriptor instead.
func (*ClusterInfoRequest) Descriptor() ([]byte, []int) {
	return file_dfs_proto_rawDescGZIP(), []int{17}
}

// Represents a storage node's runtime stats
type NodeStats struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeInfo      *NodeInfo              `protobuf:"bytes,1,opt,name=node_info,json=nodeInfo,proto3" json:"node_info,omitempty"`           // id, hostname, port
	FreeSpace     uint64                 `protobuf:"varint,2,opt,name=free_space,json=freeSpace,proto3" json:"free_space,omitempty"`       // free space
	NumRequests   uint64                 `protobuf:"varint,3,opt,name=num_requests,json=numRequests,proto3" json:"num_requests,omitempty"` // request count
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeStats) Reset() {
	*x = NodeStats{}
	mi := &file_dfs_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeStats) ProtoMessage() {}

func (x *NodeStats) ProtoReflect() protoreflect.Message {
	mi := &file_dfs_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeStats.ProtoReflect.Descriptor instead.
func (*NodeStats) Descriptor() ([]byte, []int) {
	return file_dfs_proto_rawDescGZIP(), []int{18}
}

func (x *NodeStats) GetNodeInfo() *NodeInfo {
	if x != nil {
		return x.NodeInfo
	}
	return nil
}

func (x *NodeStats) GetFreeSpace() uint64 {
	if x != nil {
		return x.FreeSpace
	}
	return 0
}

func (x *NodeStats) GetNumRequests() uint64 {
	if x != nil {
		return x.NumRequests
	}
	return 0
}

// Controller -> Client
type ClusterInfoResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	NodeStats      []*NodeStats           `protobuf:"bytes,1,rep,name=node_stats,json=nodeStats,proto3" json:"node_stats,omitempty"`
	TotalFreeSpace uint64                 `protobuf:"varint,2,opt,name=total_free_space,json=totalFreeSpace,proto3" json:"total_free_space,omitempty"` // total across all nodes
	TotalRequests  uint64                 `protobuf:"varint,3,opt,name=total_requests,json=totalRequests,proto3" json:"total_requests,omitempty"`      // total request count
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ClusterInfoResponse) Reset() {
	*x = ClusterInfoResponse{}
	mi := &file_dfs_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClusterInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClusterInfoResponse) ProtoMessage() {}

func (x *ClusterInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dfs_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClusterInfoResponse.ProtoReflect.Descriptor instead.
func (*ClusterInfoResponse) Descriptor() ([]byte, []int) {
	return file_dfs_proto_rawDescGZIP(), []int{19}
}

func (x *ClusterInfoResponse) GetNodeStats() []*NodeStats {
	if x != nil {
		return x.NodeStats
	}
	return nil
}

func (x *ClusterInfoResponse) GetTotalFreeSpace() uint64 {
	if x != nil {
		return x.TotalFreeSpace
	}
	return 0
}

func (x *ClusterInfoResponse) GetTotalRequests() uint64 {
	if x != nil {
		return x.TotalRequests
	}
	return 0
}

// Client -> Storage AND Storage -> Storage
type StoreChunkRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChunkInfo     *ChunkInfo             `protobuf:"bytes,1,opt,name=chunk_info,json=chunkInfo,proto3" json:"chunk_info,omitempty"` // filename + chunk index
	ChunkData     []byte                 `protobuf:"bytes,2,opt,name=chunk_data,json=chunkData,proto3" json:"chunk_data,omitempty"`
	Checksum      []byte                 `protobuf:"bytes,3,opt,name=checksum,proto3" json:"checksum,omitempty"`
	Pipeline      []*NodeInfo            `protobuf:"bytes,4,rep,name=pipeline,proto3" json:"pipeline,omitempty"` // next remaining nodes in the pipeline
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StoreChunkRequest) Reset() {
	*x = StoreChunkRequest{}
	mi := &file_dfs_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StoreChunkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StoreChunkRequest) ProtoMessage() {}

func (x *StoreChunkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dfs_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StoreChunkRequest.ProtoReflect.Descriptor instead.
func (*StoreChunkRequest) Descriptor() ([]byte, []int) {
	return file_dfs_proto_rawDescGZIP(), []int{20}
}

func (x *StoreChunkRequest) GetChunkInfo() *ChunkInfo {
	if x != nil {
		return x.ChunkInfo
	}
	return nil
}

func (x *StoreChunkRequest) GetChunkData() []byte {
	if x != nil {
		return x.ChunkData
	}
	return nil
}

func (x *StoreChunkRequest) GetChecksum() []byte {
	if x != nil {
		return x.Checksum
	}
	return nil
}

func (x *StoreChunkRequest) GetPipeline() []*NodeInfo {
	if x != nil {
		return x.Pipeline
	}
	return nil
}

// Storage -> Client
type StoreChunkResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`                               // success or fail
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`                          // empty if ok=true
	ChunkInfo     *ChunkInfo             `protobuf:"bytes,3,opt,name=chunk_info,json=chunkInfo,proto3" json:"chunk_info,omitempty"` // which chunk was successfully saved (useful for error reporting)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StoreChunkResponse) Reset() {
	*x = StoreChunkResponse{}
	mi := &file_dfs_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StoreChunkResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StoreChunkResponse) ProtoMessage() {}

func (x *StoreChunkResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dfs_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StoreChunkResponse.ProtoReflect.Descriptor instead.
func (*StoreChunkResponse) Descriptor() ([]byte, []int) {
	return file_dfs_proto_rawDescGZIP(), []int{21}
}

func (x *StoreChunkResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *StoreChunkResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *StoreChunkResponse) GetChunkInfo() *ChunkInfo {
	if x != nil {
		return x.ChunkInfo
	}
	return nil
}

// Client -> Storage
type RetrieveChunkRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChunkInfo     *ChunkInfo             `protobuf:"bytes,1,opt,name=chunk_info,json=chunkInfo,proto3" json:"chunk_info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RetrieveChunkRequest) Reset() {
	*x = RetrieveChunkRequest{}
	mi := &file_dfs_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RetrieveChunkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RetrieveChunkRequest) ProtoMessage() {}

func (x *RetrieveChunkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dfs_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RetrieveChunkRequest.ProtoReflect.Descriptor instead.
func (*RetrieveChunkRequest) Descriptor() ([]byte, []int) {
	return file_dfs_proto_rawDescGZIP(), []int{22}
}

func (x *RetrieveChunkRequest) GetChunkInfo() *ChunkInfo {
	if x != nil {
		return x.ChunkInfo
	}
	return nil
}

// Storage -> Client
type RetrieveChunkResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"` // empty if ok=true
	ChunkData     []byte                 `protobuf:"bytes,3,opt,name=chunk_data,json=chunkData,proto3" json:"chunk_data,omitempty"`
	Checksum      []byte                 `protobuf:"bytes,4,opt,name=checksum,proto3" json:"checksum,omitempty"` // client should verify checksum, if corrupted ask from one of the replicas
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RetrieveChunkResponse) Reset() {
	*x = RetrieveChunkResponse{}
	mi := &file_dfs_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RetrieveChunkResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RetrieveChunkResponse) ProtoMessage() {}

func (x *RetrieveChunkResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dfs_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RetrieveChunkResponse.ProtoReflect.Descriptor instead.
func (*RetrieveChunkResponse) Descriptor() ([]byte, []int) {
	return file_dfs_proto_rawDescGZIP(), []int{23}
}

func (x *RetrieveChunkResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *RetrieveChunkResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *RetrieveChunkResponse) GetChunkData() []byte {
	if x != nil {
		return x.ChunkData
	}
	return nil
}

func (x *RetrieveChunkResponse) GetChecksum() []byte {
	if x != nil {
		return x.Checksum
	}
	return nil
}

// Controller -> Storage
// Controller issues deletion instead of client
type DeleteChunkRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChunkInfo     *ChunkInfo             `protobuf:"bytes,1,opt,name=chunk_info,json=chunkInfo,proto3" json:"chunk_info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteChunkRequest) Reset() {
	*x = DeleteChunkRequest{}
	mi := &file_dfs_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteChunkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteChunkRequest) ProtoMessage() {}

func (x *DeleteChunkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dfs_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteChunkRequest.ProtoReflect.Descriptor instead.
func (*DeleteChunkRequest) Descriptor() ([]byte, []int) {
	return file_dfs_proto_rawDescGZIP(), []int{24}
}

func (x *DeleteChunkRequest) GetChunkInfo() *ChunkInfo {
	if x != nil {
		return x.ChunkInfo
	}
	return nil
}

type DeleteChunkResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	ChunkInfo     *ChunkInfo             `protobuf:"bytes,3,opt,name=chunk_info,json=chunkInfo,proto3" json:"chunk_info,omitempty"` // so Controller knows which chunk this ack is for
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteChunkResponse) Reset() {
	*x = DeleteChunkResponse{}
	mi := &file_dfs_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteChunkResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteChunkResponse) ProtoMessage() {}

func (x *DeleteChunkResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dfs_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteChunkResponse.ProtoReflect.Descriptor instead.
func (*DeleteChunkResponse) Descriptor() ([]byte, []int) {
	return file_dfs_proto_rawDescGZIP(), []int{25}
}

func (x *DeleteChunkResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *DeleteChunkResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *DeleteChunkResponse) GetChunkInfo() *ChunkInfo {
	if x != nil {
		return x.ChunkInfo
	}
	return nil
}

type Wrapper struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Msg:
	//
	//	*Wrapper_RegisterRequest
	//	*Wrapper_RegisterResponse
	//	*Wrapper_Heartbeat
	//	*Wrapper_HeartbeatResponse
	//	*Wrapper_ReplicateRequest
	//	*Wrapper_StoreRequest
	//	*Wrapper_StoreResponse
	//	*Wrapper_RetrieveRequest
	//	*Wrapper_RetrieveResponse
	//	*Wrapper_DeleteRequest
	//	*Wrapper_DeleteResponse
	//	*Wrapper_ListRequest
	//	*Wrapper_ListResponse
	//	*Wrapper_ClusterInfoRequest
	//	*Wrapper_ClusterInfoResponse
	//	*Wrapper_StoreChunkRequest
	//	*Wrapper_StoreChunkResponse
	//	*Wrapper_RetrieveChunkRequest
	//	*Wrapper_RetrieveChunkResponse
	//	*Wrapper_DeleteChunkRequest
	//	*Wrapper_DeleteChunkResponse
	Msg           isWrapper_Msg `protobuf_oneof:"msg"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Wrapper) Reset() {
	*x = Wrapper{}
	mi := &file_dfs_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Wrapper) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Wrapper) ProtoMessage() {}

func (x *Wrapper) ProtoReflect() protoreflect.Message {
	mi := &file_dfs_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Wrapper.ProtoReflect.Descriptor instead.
func (*Wrapper) Descriptor() ([]byte, []int) {
	return file_dfs_proto_rawDescGZIP(), []int{26}
}

func (x *Wrapper) GetMsg() isWrapper_Msg {
	if x != nil {
		return x.Msg
	}
	return nil
}

func (x *Wrapper) GetRegisterRequest() *RegisterRequest {
	if x != nil {
		if x, ok := x.Msg.(*Wrapper_RegisterRequest); ok {
			return x.RegisterRequest
		}
	}
	return nil
}

func (x *Wrapper) GetRegisterResponse() *RegisterResponse {
	if x != nil {
		if x, ok := x.Msg.(*Wrapper_RegisterResponse); ok {
			return x.RegisterResponse
		}
	}
	return nil
}

func (x *Wrapper) GetHeartbeat() *Heartbeat {
	if x != nil {
		if x, ok := x.Msg.(*Wrapper_Heartbeat); ok {
			return x.Heartbeat
		}
	}
	return nil
}

func (x *Wrapper) GetHeartbeatResponse() *HeartbeatResponse {
	if x != nil {
		if x, ok := x.Msg.(*Wrapper_HeartbeatResponse); ok {
			return x.HeartbeatResponse
		}
	}
	return nil
}

func (x *Wrapper) GetReplicateRequest() *ReplicateRequest {
	if x != nil {
		if x, ok := x.Msg.(*Wrapper_ReplicateRequest); ok {
			return x.ReplicateRequest
		}
	}
	return nil
}

func (x *Wrapper) GetStoreRequest() *StoreRequest {
	if x != nil {
		if x, ok := x.Msg.(*Wrapper_StoreRequest); ok {
			return x.StoreRequest
		}
	}
	return nil
}

func (x *Wrapper) GetStoreResponse() *StoreResponse {
	if x != nil {
		if x, ok := x.Msg.(*Wrapper_StoreResponse); ok {
			return x.StoreResponse
		}
	}
	return nil
}

func (x *Wrapper) GetRetrieveRequest() *RetrieveRequest {
	if x != nil {
		if x, ok := x.Msg.(*Wrapper_RetrieveRequest); ok {
			return x.RetrieveRequest
		}
	}
	return nil
}

func (x *Wrapper) GetRetrieveResponse() *RetrieveResponse {
	if x != nil {
		if x, ok := x.Msg.(*Wrapper_RetrieveResponse); ok {
			return x.RetrieveResponse
		}
	}
	return nil
}

func (x *Wrapper) GetDeleteRequest() *DeleteRequest {
	if x != nil {
		if x, ok := x.Msg.(*Wrapper_DeleteRequest); ok {
			return x.DeleteRequest
		}
	}
	return nil
}

func (x *Wrapper) GetDeleteResponse() *DeleteResponse {
	if x != nil {
		if x, ok := x.Msg.(*Wrapper_DeleteResponse); ok {
			return x.DeleteResponse
		}
	}
	return nil
}

func (x *Wrapper) GetListRequest() *ListRequest {
	if x != nil {
		if x, ok := x.Msg.(*Wrapper_ListRequest); ok {
			return x.ListRequest
		}
	}
	return nil
}

func (x *Wrapper) GetListResponse() *ListResponse {
	if x != nil {
		if x, ok := x.Msg.(*Wrapper_ListResponse); ok {
			return x.ListResponse
		}
	}
	return nil
}

func (x *Wrapper) GetClusterInfoRequest() *ClusterInfoRequest {
	if x != nil {
		if x, ok := x.Msg.(*Wrapper_ClusterInfoRequest); ok {
			return x.ClusterInfoRequest
		}
	}
	return nil
}

func (x *Wrapper) GetClusterInfoResponse() *ClusterInfoResponse {
	if x != nil {
		if x, ok := x.Msg.(*Wrapper_ClusterInfoResponse); ok {
			return x.ClusterInfoResponse
		}
	}
	return nil
}

func (x *Wrapper) GetStoreChunkRequest() *StoreChunkRequest {
	if x != nil {
		if x, ok := x.Msg.(*Wrapper_StoreChunkRequest); ok {
			return x.StoreChunkRequest
		}
	}
	return nil
}

func (x *Wrapper) GetStoreChunkResponse() *StoreChunkResponse {
	if x != nil {
		if x, ok := x.Msg.(*Wrapper_StoreChunkResponse); ok {
			return x.StoreChunkResponse
		}
	}
	return nil
}

func (x *Wrapper) GetRetrieveChunkRequest() *RetrieveChunkRequest {
	if x != nil {
		if x, ok := x.Msg.(*Wrapper_RetrieveChunkRequest); ok {
			return x.RetrieveChunkRequest
		}
	}
	return nil
}

func (x *Wrapper) GetRetrieveChunkResponse() *RetrieveChunkResponse {
	if x != nil {
		if x, ok := x.Msg.(*Wrapper_RetrieveChunkResponse); ok {
			return x.RetrieveChunkResponse
		}
	}
	return nil
}

func (x *Wrapper) GetDeleteChunkRequest() *DeleteChunkRequest {
	if x != nil {
		if x, ok := x.Msg.(*Wrapper_DeleteChunkRequest); ok {
			return x.DeleteChunkRequest
		}
	}
	return nil
}

func (x *Wrapper) GetDeleteChunkResponse() *DeleteChunkResponse {
	if x != nil {
		if x, ok := x.Msg.(*Wrapper_DeleteChunkResponse); ok {
			return x.DeleteChunkResponse
		}
	}
	return nil
}

type isWrapper_Msg interface {
	isWrapper_Msg()
}

type Wrapper_RegisterRequest struct {
	// Controller <-> Storage
	RegisterRequest *RegisterRequest `protobuf:"bytes,1,opt,name=register_request,json=registerRequest,proto3,oneof"`
}

type Wrapper_RegisterResponse struct {
	RegisterResponse *RegisterResponse `protobuf:"bytes,2,opt,name=register_response,json=registerResponse,proto3,oneof"`
}

type Wrapper_Heartbeat struct {
	Heartbeat *Heartbeat `protobuf:"bytes,3,opt,name=heartbeat,proto3,oneof"`
}

type Wrapper_HeartbeatResponse struct {
	HeartbeatResponse *HeartbeatResponse `protobuf:"bytes,4,opt,name=heartbeat_response,json=heartbeatResponse,proto3,oneof"`
}

type Wrapper_ReplicateRequest struct {
	ReplicateRequest *ReplicateRequest `protobuf:"bytes,5,opt,name=replicate_request,json=replicateRequest,proto3,oneof"`
}

type Wrapper_StoreRequest struct {
	// Client <-> Controller
	StoreRequest *StoreRequest `protobuf:"bytes,6,opt,name=store_request,json=storeRequest,proto3,oneof"`
}

type Wrapper_StoreResponse struct {
	StoreResponse *StoreResponse `protobuf:"bytes,7,opt,name=store_response,json=storeResponse,proto3,oneof"`
}

type Wrapper_RetrieveRequest struct {
	RetrieveRequest *RetrieveRequest `protobuf:"bytes,8,opt,name=retrieve_request,json=retrieveRequest,proto3,oneof"`
}

type Wrapper_RetrieveResponse struct {
	RetrieveResponse *RetrieveResponse `protobuf:"bytes,9,opt,name=retrieve_response,json=retrieveResponse,proto3,oneof"`
}

type Wrapper_DeleteRequest struct {
	DeleteRequest *DeleteRequest `protobuf:"bytes,10,opt,name=delete_request,json=deleteRequest,proto3,oneof"`
}

type Wrapper_DeleteResponse struct {
	DeleteResponse *DeleteResponse `protobuf:"bytes,11,opt,name=delete_response,json=deleteResponse,proto3,oneof"`
}

type Wrapper_ListRequest struct {
	ListRequest *ListRequest `protobuf:"bytes,12,opt,name=list_request,json=listRequest,proto3,oneof"`
}

type Wrapper_ListResponse struct {
	ListResponse *ListResponse `protobuf:"bytes,13,opt,name=list_response,json=listResponse,proto3,oneof"`
}

type Wrapper_ClusterInfoRequest struct {
	ClusterInfoRequest *ClusterInfoRequest `protobuf:"bytes,14,opt,name=cluster_info_request,json=clusterInfoRequest,proto3,oneof"`
}

type Wrapper_ClusterInfoResponse struct {
	ClusterInfoResponse *ClusterInfoResponse `protobuf:"bytes,15,opt,name=cluster_info_response,json=clusterInfoResponse,proto3,oneof"`
}

type Wrapper_StoreChunkRequest struct {
	// Client <-> Storage
	StoreChunkRequest *StoreChunkRequest `protobuf:"bytes,16,opt,name=store_chunk_request,json=storeChunkRequest,proto3,oneof"`
}

type Wrapper_StoreChunkResponse struct {
	StoreChunkResponse *StoreChunkResponse `protobuf:"bytes,17,opt,name=store_chunk_response,json=storeChunkResponse,proto3,oneof"`
}

type Wrapper_RetrieveChunkRequest struct {
	RetrieveChunkRequest *RetrieveChunkRequest `protobuf:"bytes,18,opt,name=retrieve_chunk_request,json=retrieveChunkRequest,proto3,oneof"`
}

type Wrapper_RetrieveChunkResponse struct {
	RetrieveChunkResponse *RetrieveChunkResponse `protobuf:"bytes,19,opt,name=retrieve_chunk_response,json=retrieveChunkResponse,proto3,oneof"`
}

type Wrapper_DeleteChunkRequest struct {
	// Controller <-> Storage
	DeleteChunkRequest *DeleteChunkRequest `protobuf:"bytes,20,opt,name=delete_chunk_request,json=deleteChunkRequest,proto3,oneof"`
}

type Wrapper_DeleteChunkResponse struct {
	DeleteChunkResponse *DeleteChunkResponse `protobuf:"bytes,21,opt,name=delete_chunk_response,json=deleteChunkResponse,proto3,oneof"`
}

func (*Wrapper_RegisterRequest) isWrapper_Msg() {}

func (*Wrapper_RegisterResponse) isWrapper_Msg() {}

func (*Wrapper_Heartbeat) isWrapper_Msg() {}

func (*Wrapper_HeartbeatResponse) isWrapper_Msg() {}

func (*Wrapper_ReplicateRequest) isWrapper_Msg() {}

func (*Wrapper_StoreRequest) isWrapper_Msg() {}

func (*Wrapper_StoreResponse) isWrapper_Msg() {}

func (*Wrapper_RetrieveRequest) isWrapper_Msg() {}

func (*Wrapper_RetrieveResponse) isWrapper_Msg() {}

func (*Wrapper_DeleteRequest) isWrapper_Msg() {}

func (*Wrapper_DeleteResponse) isWrapper_Msg() {}

func (*Wrapper_ListRequest) isWrapper_Msg() {}

func (*Wrapper_ListResponse) isWrapper_Msg() {}

func (*Wrapper_ClusterInfoRequest) isWrapper_Msg() {}

func (*Wrapper_ClusterInfoResponse) isWrapper_Msg() {}

func (*Wrapper_StoreChunkRequest) isWrapper_Msg() {}

func (*Wrapper_StoreChunkResponse) isWrapper_Msg() {}

func (*Wrapper_RetrieveChunkRequest) isWrapper_Msg() {}

func (*Wrapper_RetrieveChunkResponse) isWrapper_Msg() {}

func (*Wrapper_DeleteChunkRequest) isWrapper_Msg() {}

func (*Wrapper_DeleteChunkResponse) isWrapper_Msg() {}

var File_dfs_proto protoreflect.FileDescriptor

const file_dfs_proto_rawDesc = "" +
	"\n" +
	"\tdfs.proto\"`\n" +
	"\x0fRegisterRequest\x12\x1a\n" +
	"\bhostname\x18\x01 \x01(\tR\bhostname\x12\x12\n" +
	"\x04port\x18\x02 \x01(\x05R\x04port\x12\x1d\n" +
	"\n" +
	"free_space\x18\x03 \x01(\x04R\tfreeSpace\"Q\n" +
	"\x10RegisterResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12\x17\n" +
	"\anode_id\x18\x02 \x01(\rR\x06nodeId\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\"\x8f\x01\n" +
	"\tHeartbeat\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\rR\x06nodeId\x12\x1d\n" +
	"\n" +
	"free_space\x18\x02 \x01(\x04R\tfreeSpace\x12\x1f\n" +
	"\vnum_request\x18\x03 \x01(\x04R\n" +
	"numRequest\x12)\n" +
	"\n" +
	"new_chunks\x18\x04 \x03(\v2\n" +
	".ChunkInfoR\tnewChunks\"e\n" +
	"\x11HeartbeatResponse\x12\x10\n" +
	"\x03ack\x18\x01 \x01(\bR\x03ack\x12>\n" +
	"\x11replicate_request\x18\x02 \x03(\v2\x11.ReplicateRequestR\x10replicateRequest\"s\n" +
	"\x10ReplicateRequest\x12\x19\n" +
	"\bsrc_host\x18\x01 \x01(\tR\asrcHost\x12\x19\n" +
	"\bsrc_port\x18\x02 \x01(\x05R\asrcPort\x12)\n" +
	"\n" +
	"chunk_info\x18\x03 \x01(\v2\n" +
	".ChunkInfoR\tchunkInfo\"H\n" +
	"\tChunkInfo\x12\x1a\n" +
	"\bfilename\x18\x01 \x01(\tR\bfilename\x12\x1f\n" +
	"\vchunk_index\x18\x02 \x01(\rR\n" +
	"chunkIndex\"S\n" +
	"\bNodeInfo\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\rR\x06nodeId\x12\x1a\n" +
	"\bhostname\x18\x02 \x01(\tR\bhostname\x12\x12\n" +
	"\x04port\x18\x03 \x01(\x05R\x04port\"Z\n" +
	"\fChunkMapping\x12)\n" +
	"\n" +
	"chunk_info\x18\x01 \x01(\v2\n" +
	".ChunkInfoR\tchunkInfo\x12\x1f\n" +
	"\x05nodes\x18\x02 \x03(\v2\t.NodeInfoR\x05nodes\"\x87\x01\n" +
	"\fStoreRequest\x12\x1a\n" +
	"\bfilename\x18\x01 \x01(\tR\bfilename\x12\x1f\n" +
	"\vchunk_count\x18\x02 \x01(\rR\n" +
	"chunkCount\x12\x1d\n" +
	"\n" +
	"chunk_size\x18\x03 \x01(\x04R\tchunkSize\x12\x1b\n" +
	"\tfile_size\x18\x04 \x01(\x04R\bfileSize\"h\n" +
	"\rStoreResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\x121\n" +
	"\fdestinations\x18\x03 \x03(\v2\r.ChunkMappingR\fdestinations\"-\n" +
	"\x0fRetrieveRequest\x12\x1a\n" +
	"\bfilename\x18\x01 \x01(\tR\bfilename\"e\n" +
	"\x10RetrieveResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\x12+\n" +
	"\tlocations\x18\x03 \x03(\v2\r.ChunkMappingR\tlocations\"+\n" +
	"\rDeleteRequest\x12\x1a\n" +
	"\bfilename\x18\x01 \x01(\tR\bfilename\"6\n" +
	"\x0eDeleteResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"\r\n" +
	"\vListRequest\"d\n" +
	"\bFileInfo\x12\x1a\n" +
	"\bfilename\x18\x01 \x01(\tR\bfilename\x12\x1b\n" +
	"\tfile_size\x18\x02 \x01(\x04R\bfileSize\x12\x1f\n" +
	"\vchunk_count\x18\x03 \x01(\rR\n" +
	"chunkCount\"U\n" +
	"\fListResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\x12\x1f\n" +
	"\x05files\x18\x03 \x03(\v2\t.FileInfoR\x05files\"\x14\n" +
	"\x12ClusterInfoRequest\"u\n" +
	"\tNodeStats\x12&\n" +
	"\tnode_info\x18\x01 \x01(\v2\t.NodeInfoR\bnodeInfo\x12\x1d\n" +
	"\n" +
	"free_space\x18\x02 \x01(\x04R\tfreeSpace\x12!\n" +
	"\fnum_requests\x18\x03 \x01(\x04R\vnumRequests\"\x91\x01\n" +
	"\x13ClusterInfoResponse\x12)\n" +
	"\n" +
	"node_stats\x18\x01 \x03(\v2\n" +
	".NodeStatsR\tnodeStats\x12(\n" +
	"\x10total_free_space\x18\x02 \x01(\x04R\x0etotalFreeSpace\x12%\n" +
	"\x0etotal_requests\x18\x03 \x01(\x04R\rtotalRequests\"\xa0\x01\n" +
	"\x11StoreChunkRequest\x12)\n" +
	"\n" +
	"chunk_info\x18\x01 \x01(\v2\n" +
	".ChunkInfoR\tchunkInfo\x12\x1d\n" +
	"\n" +
	"chunk_data\x18\x02 \x01(\fR\tchunkData\x12\x1a\n" +
	"\bchecksum\x18\x03 \x01(\fR\bchecksum\x12%\n" +
	"\bpipeline\x18\x04 \x03(\v2\t.NodeInfoR\bpipeline\"e\n" +
	"\x12StoreChunkResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\x12)\n" +
	"\n" +
	"chunk_info\x18\x03 \x01(\v2\n" +
	".ChunkInfoR\tchunkInfo\"A\n" +
	"\x14RetrieveChunkRequest\x12)\n" +
	"\n" +
	"chunk_info\x18\x01 \x01(\v2\n" +
	".ChunkInfoR\tchunkInfo\"x\n" +
	"\x15RetrieveChunkResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\x12\x1d\n" +
	"\n" +
	"chunk_data\x18\x03 \x01(\fR\tchunkData\x12\x1a\n" +
	"\bchecksum\x18\x04 \x01(\fR\bchecksum\"?\n" +
	"\x12DeleteChunkRequest\x12)\n" +
	"\n" +
	"chunk_info\x18\x01 \x01(\v2\n" +
	".ChunkInfoR\tchunkInfo\"f\n" +
	"\x13DeleteChunkResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\x12)\n" +
	"\n" +
	"chunk_info\x18\x03 \x01(\v2\n" +
	".ChunkInfoR\tchunkInfo\"\xec\n" +
	"\n" +
	"\aWrapper\x12=\n" +
	"\x10register_request\x18\x01 \x01(\v2\x10.RegisterRequestH\x00R\x0fregisterRequest\x12@\n" +
	"\x11register_response\x18\x02 \x01(\v2\x11.RegisterResponseH\x00R\x10registerResponse\x12*\n" +
	"\theartbeat\x18\x03 \x01(\v2\n" +
	".HeartbeatH\x00R\theartbeat\x12C\n" +
	"\x12heartbeat_response\x18\x04 \x01(\v2\x12.HeartbeatResponseH\x00R\x11heartbeatResponse\x12@\n" +
	"\x11replicate_request\x18\x05 \x01(\v2\x11.ReplicateRequestH\x00R\x10replicateRequest\x124\n" +
	"\rstore_request\x18\x06 \x01(\v2\r.StoreRequestH\x00R\fstoreRequest\x127\n" +
	"\x0estore_response\x18\a \x01(\v2\x0e.StoreResponseH\x00R\rstoreResponse\x12=\n" +
	"\x10retrieve_request\x18\b \x01(\v2\x10.RetrieveRequestH\x00R\x0fretrieveRequest\x12@\n" +
	"\x11retrieve_response\x18\t \x01(\v2\x11.RetrieveResponseH\x00R\x10retrieveResponse\x127\n" +
	"\x0edelete_request\x18\n" +
	" \x01(\v2\x0e.DeleteRequestH\x00R\rdeleteRequest\x12:\n" +
	"\x0fdelete_response\x18\v \x01(\v2\x0f.DeleteResponseH\x00R\x0edeleteResponse\x121\n" +
	"\flist_request\x18\f \x01(\v2\f.ListRequestH\x00R\vlistRequest\x124\n" +
	"\rlist_response\x18\r \x01(\v2\r.ListResponseH\x00R\flistResponse\x12G\n" +
	"\x14cluster_info_request\x18\x0e \x01(\v2\x13.ClusterInfoRequestH\x00R\x12clusterInfoRequest\x12J\n" +
	"\x15cluster_info_response\x18\x0f \x01(\v2\x14.ClusterInfoResponseH\x00R\x13clusterInfoResponse\x12D\n" +
	"\x13store_chunk_request\x18\x10 \x01(\v2\x12.StoreChunkRequestH\x00R\x11storeChunkRequest\x12G\n" +
	"\x14store_chunk_response\x18\x11 \x01(\v2\x13.StoreChunkResponseH\x00R\x12storeChunkResponse\x12M\n" +
	"\x16retrieve_chunk_request\x18\x12 \x01(\v2\x15.RetrieveChunkRequestH\x00R\x14retrieveChunkRequest\x12P\n" +
	"\x17retrieve_chunk_response\x18\x13 \x01(\v2\x16.RetrieveChunkResponseH\x00R\x15retrieveChunkResponse\x12G\n" +
	"\x14delete_chunk_request\x18\x14 \x01(\v2\x13.DeleteChunkRequestH\x00R\x12deleteChunkRequest\x12J\n" +
	"\x15delete_chunk_response\x18\x15 \x01(\v2\x14.DeleteChunkResponseH\x00R\x13deleteChunkResponseB\x05\n" +
	"\x03msgB*Z(github.com/erwannd/dfs/messages;messagesb\x06proto3"

var (
	file_dfs_proto_rawDescOnce sync.Once
	file_dfs_proto_rawDescData []byte
)

func file_dfs_proto_rawDescGZIP() []byte {
	file_dfs_proto_rawDescOnce.Do(func() {
		file_dfs_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_dfs_proto_rawDesc), len(file_dfs_proto_rawDesc)))
	})
	return file_dfs_proto_rawDescData
}

var file_dfs_proto_msgTypes = make([]protoimpl.MessageInfo, 27)
var file_dfs_proto_goTypes = []any{
	(*RegisterRequest)(nil),       // 0: RegisterRequest
	(*RegisterResponse)(nil),      // 1: RegisterResponse
	(*Heartbeat)(nil),             // 2: Heartbeat
	(*HeartbeatResponse)(nil),     // 3: HeartbeatResponse
	(*ReplicateRequest)(nil),      // 4: ReplicateRequest
	(*ChunkInfo)(nil),             // 5: ChunkInfo
	(*NodeInfo)(nil),              // 6: NodeInfo
	(*ChunkMapping)(nil),          // 7: ChunkMapping
	(*StoreRequest)(nil),          // 8: StoreRequest
	(*StoreResponse)(nil),         // 9: StoreResponse
	(*RetrieveRequest)(nil),       // 10: RetrieveRequest
	(*RetrieveResponse)(nil),      // 11: RetrieveResponse
	(*DeleteRequest)(nil),         // 12: DeleteRequest
	(*DeleteResponse)(nil),        // 13: DeleteResponse
	(*ListRequest)(nil),           // 14: ListRequest
	(*FileInfo)(nil),              // 15: FileInfo
	(*ListResponse)(nil),          // 16: ListResponse
	(*ClusterInfoRequest)(nil),    // 17: ClusterInfoRequest
	(*NodeStats)(nil),             // 18: NodeStats
	(*ClusterInfoResponse)(nil),   // 19: ClusterInfoResponse
	(*StoreChunkRequest)(nil),     // 20: StoreChunkRequest
	(*StoreChunkResponse)(nil),    // 21: StoreChunkResponse
	(*RetrieveChunkRequest)(nil),  // 22: RetrieveChunkRequest
	(*RetrieveChunkResponse)(nil), // 23: RetrieveChunkResponse
	(*DeleteChunkRequest)(nil),    // 24: DeleteChunkRequest
	(*DeleteChunkResponse)(nil),   // 25: DeleteChunkResponse
	(*Wrapper)(nil),               // 26: Wrapper
}
var file_dfs_proto_depIdxs = []int32{
	5,  // 0: Heartbeat.new_chunks:type_name -> ChunkInfo
	4,  // 1: HeartbeatResponse.replicate_request:type_name -> ReplicateRequest
	5,  // 2: ReplicateRequest.chunk_info:type_name -> ChunkInfo
	5,  // 3: ChunkMapping.chunk_info:type_name -> ChunkInfo
	6,  // 4: ChunkMapping.nodes:type_name -> NodeInfo
	7,  // 5: StoreResponse.destinations:type_name -> ChunkMapping
	7,  // 6: RetrieveResponse.locations:type_name -> ChunkMapping
	15, // 7: ListResponse.files:type_name -> FileInfo
	6,  // 8: NodeStats.node_info:type_name -> NodeInfo
	18, // 9: ClusterInfoResponse.node_stats:type_name -> NodeStats
	5,  // 10: StoreChunkRequest.chunk_info:type_name -> ChunkInfo
	6,  // 11: StoreChunkRequest.pipeline:type_name -> NodeInfo
	5,  // 12: StoreChunkResponse.chunk_info:type_name -> ChunkInfo
	5,  // 13: RetrieveChunkRequest.chunk_info:type_name -> ChunkInfo
	5,  // 14: DeleteChunkRequest.chunk_info:type_name -> ChunkInfo
	5,  // 15: DeleteChunkResponse.chunk_info:type_name -> ChunkInfo
	0,  // 16: Wrapper.register_request:type_name -> RegisterRequest
	1,  // 17: Wrapper.register_response:type_name -> RegisterResponse
	2,  // 18: Wrapper.heartbeat:type_name -> Heartbeat
	3,  // 19: Wrapper.heartbeat_response:type_name -> HeartbeatResponse
	4,  // 20: Wrapper.replicate_request:type_name -> ReplicateRequest
	8,  // 21: Wrapper.store_request:type_name -> StoreRequest
	9,  // 22: Wrapper.store_response:type_name -> StoreResponse
	10, // 23: Wrapper.retrieve_request:type_name -> RetrieveRequest
	11, // 24: Wrapper.retrieve_response:type_name -> RetrieveResponse
	12, // 25: Wrapper.delete_request:type_name -> DeleteRequest
	13, // 26: Wrapper.delete_response:type_name -> DeleteResponse
	14, // 27: Wrapper.list_request:type_name -> ListRequest
	16, // 28: Wrapper.list_response:type_name -> ListResponse
	17, // 29: Wrapper.cluster_info_request:type_name -> ClusterInfoRequest
	19, // 30: Wrapper.cluster_info_response:type_name -> ClusterInfoResponse
	20, // 31: Wrapper.store_chunk_request:type_name -> StoreChunkRequest
	21, // 32: Wrapper.store_chunk_response:type_name -> StoreChunkResponse
	22, // 33: Wrapper.retrieve_chunk_request:type_name -> RetrieveChunkRequest
	23, // 34: Wrapper.retrieve_chunk_response:type_name -> RetrieveChunkResponse
	24, // 35: Wrapper.delete_chunk_request:type_name -> DeleteChunkRequest
	25, // 36: Wrapper.delete_chunk_response:type_name -> DeleteChunkResponse
	37, // [37:37] is the sub-list for method output_type
	37, // [37:37] is the sub-list for method input_type
	37, // [37:37] is the sub-list for extension type_name
	37, // [37:37] is the sub-list for extension extendee
	0,  // [0:37] is the sub-list for field type_name
}

func init() { file_dfs_proto_init() }
func file_dfs_proto_init() {
	if File_dfs_proto != nil {
		return
	}
	file_dfs_proto_msgTypes[26].OneofWrappers = []any{
		(*Wrapper_RegisterRequest)(nil),
		(*Wrapper_RegisterResponse)(nil),
		(*Wrapper_Heartbeat)(nil),
		(*Wrapper_HeartbeatResponse)(nil),
		(*Wrapper_ReplicateRequest)(nil),
		(*Wrapper_StoreRequest)(nil),
		(*Wrapper_StoreResponse)(nil),
		(*Wrapper_RetrieveRequest)(nil),
		(*Wrapper_RetrieveResponse)(nil),
		(*Wrapper_DeleteRequest)(nil),
		(*Wrapper_DeleteResponse)(nil),
		(*Wrapper_ListRequest)(nil),
		(*Wrapper_ListResponse)(nil),
		(*Wrapper_ClusterInfoRequest)(nil),
		(*Wrapper_ClusterInfoResponse)(nil),
		(*Wrapper_StoreChunkRequest)(nil),
		(*Wrapper_StoreChunkResponse)(nil),
		(*Wrapper_RetrieveChunkRequest)(nil),
		(*Wrapper_RetrieveChunkResponse)(nil),
		(*Wrapper_DeleteChunkRequest)(nil),
		(*Wrapper_DeleteChunkResponse)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_dfs_proto_rawDesc), len(file_dfs_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   27,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_dfs_proto_goTypes,
		DependencyIndexes: file_dfs_proto_depIdxs,
		MessageInfos:      file_dfs_proto_msgTypes,
	}.Build()
	File_dfs_proto = out.File
	file_dfs_proto_goTypes = nil
	file_dfs_proto_depIdxs = nil
}
